<form id="discount-coupon-form"	 action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post"> 
    <div class="discount">
        <h2	><?php echo $this->__('Apply Coupon Code') ?></h2> 
	
        <div class="discount-form	col-lg-12 col-md-12 col-sm-12 col-xs-12 pad0 mt1em">
            <label for="coupon_code"><?php echo $this->__('Enter your coupon code if you have one.') ?></label>
            <input type="hidden" name="remove" id="remove-coupone" value="0" />
            <div class="coupon-box">
			
                 <input class="input-text" id="coupon_code" placeholder="your coupon code" 	name="coupon_code" value="<?php echo $this->escapeHtml($this->getCouponCode()) ?>" /> 
				
				 <input type="button" title="<?php echo $this->__('Apply Coupon') ?>" class="button apply_code" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply Coupon') ?>"/>
				 
					<?php if(strlen($this->getCouponCode())): ?>
						&nbsp; <input type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="button cancel_coupon" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel Coupon') ?>"/>
					<?php endif;?>
				
				
            </div>
			<div class="coupon-message" style="display:none;">
				<?php echo $this->getMessagesBlock()->toHtml() ?>
			</div>
            
        </div>
    </div>

</form>

<script type="text/javascript">

//<![CDATA[
var discountForm = new VarienForm('discount-coupon-form');
discountForm.submit = function (isRemove) {
    if (isRemove) {
        $('coupon_code').removeClassName('required-entry');
        $('remove-coupone').value = "1";
    } else {
        $('coupon_code').addClassName('required-entry');
        $('remove-coupone').value = "0";
    }
    return VarienForm.prototype.submit.bind(discountForm)();
}
//]]>

jQuery.fn.firstWord = function() {
  var text = this.text().trim().split(" ");
  var first = text.shift();
  if(first == 'Coupon' || first == 'Please')
  {
	  jQuery(".cart-message-top").css("display", "none");
	  jQuery(".coupon-message").css("display", "block");
  }
  else
  {
	  jQuery(".coupon-message").css("display", "none");
	  jQuery(".cart-message-top").css("display", "block");
  }  
};

jQuery(document).ready(function() {
   jQuery(".coupon-message .messages span").firstWord();
});
</script>
  