<style>
.modal-backdrop {
   z-index: 0;
  background-color: rgba(0, 0, 0, 0);
}
.well{
width: 78%;
margin: 60px 11% 30px;
display:none;
}

</style>
<div class="well-block" style="margin-top:0px;">
    <h1  id="login_register">Sell On mSupply</h1>
        <div id="beamaeasellerform" class="become-seller-form">
        <form name="becameaseller" id="becameaseller" method="post" action="<?php echo $this->getUrl('seller/index/saveseller')?>">
        <div class="form-list">
            <ul class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <li class=" input-box">
					<input type="text" placeholder="* Seller Name"  class="input-text required-entry" value="" name="seller_name" id="seller_name" maxlength="50">
				</li>
                <li class=" input-box">
					<input type="text" placeholder="PAN Number" class="input-text" value="" name="pan_number" id="pan_no" maxlength="10">
				</li>
                <li class=" input-box">
					<input type="text" placeholder="VAT Number" class="input-text" value="" name="vat_number" id="vat_no" maxlength="11">
				</li>
                <li class="input-box">
					<input type="text"  placeholder="* Telephone" class="input-text required-entry" value=""name="telephone" id="phone" maxlength="10">
				</li>
                <li class=" input-box">
					<input type="text"  placeholder="* Address Line 1" class="input-text required-entry" value="" name="address1" id="address1">
				</li>
               <li class=" input-box">
					<input type="text"  placeholder="Address Line 2" class="input-text" value="" name="address2" id="address2">
			   </li>
                <li class=" input-box">
					<select placeholder="City" class="validate-select" value="" name="city" id="city"><option>Bangalore</option></select>
				</li>
                <li class="input-box">
					<input type="text"  placeholder="* Pin Code"class="input-text required-entry" value="" name="pincode" id="pincode" maxlength="6"> 
				</li>
                <li class=" input-box">
					<select placeholder="State" class="validate-select" value="" name="state" id="state"><option>Karnataka</option></select>
				</li>
            </ul>
             <ul class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <li class=" input-box">
					<select placeholder="Country" class="validate-select" value="" name="country" id="country"><option>India</option></select> 
				</li>                   
                <li class="input-box">
					<input type="text"  placeholder="Contact Person Name 1" class="input-text" value="" name="contact_person_name1" id="contact_person_1"> 
				</li>
                <li class="input-box">
					<input type="text"  placeholder="Contact Person Name 2" class="input-text" value="" name="contact_person_name2" id="contact_person_2"> 
				</li>
                <li class=" input-box">
					<input type="text"  placeholder="e-mail 1" class="input-text" value="" name="email_id1" id="email_id_1">
				</li>
                <li class="input-box">
					<input type="text"  placeholder="e-mail 2" class="input-text" value="" name="email_id2" id="email_id_2"> 
				</li>
                <li class="input-box">
					<input type="text"  placeholder="Website" class="input-text validate-clean-url" value="" name="website" id="website"> 
				</li>
                <li class="input-box">
					<input type="text"  placeholder="Bank Name" class="input-text" value="" name="bank_name" id="bank_name">
				</li>
                <li class="input-box">
					<input type="text"  placeholder="Bank Account Number" class="input-text" value="" name="bank_account_number" id="bank_acc" maxlength="16"> 
				</li>
            </ul>
            <ul class="col-lg-12 col-md-12 col-xs-12 text-center">
            	<li>
            		<label for="terms">
            		<input type="checkbox"  value="Yes" name="terms_and_conditions" id="terms" class="required-entry"><span id="termserrMsg" class="agreed">I agree to</span>   
                	<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/supplier-agreement.pdf" target="__blank">Terms & Conditions</a></label>
            	</li>
            	<li><button type="submit" class="button" title="<?php echo $this->__('Submit') ?>" name="send" id="send2"><span><?php echo $this->__('Submit') ?></span></button></li>
            </ul>               
        </div>
          
    </form>
        </div>
        <div class="clearfix"></div>
    </div>


<script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('becameaseller', true);
    //]]>
</script>
<script type="text/javascript">

jQuery(document).ready(function() {
	jQuery('#becameaseller').click(function() {
		var hasError = 0;
		/** ===== Seller Name ===== **/
		jQuery(".seller-failed").hide();
		var sellernameregex =/^[a-zA-Z ]{1,50}$/;
		var sellerVal = jQuery("#seller_name").val();
		if(sellerVal != "")	{
			jQuery("#advice-required-entry-seller_name").css({
						"opacity": "0",
                        "display": "none"
						});			
		}
		if(sellerVal == "")	{
		    jQuery("#seller_name").after('<span class="seller-failed"></span>');
			jQuery("#advice-required-entry-seller_name").css({
			"opacity": "999",
			"display": "block"
			});
		}else if(!sellernameregex.test(sellerVal)) {
			jQuery("#seller_name").after('<span class="seller-failed">Enter valid seller name.</span>');
			jQuery("#advice-required-entry-seller_name").css({
			"opacity": "0",
			"display": "none"
			});
			hasError = 1;
		}
		/** ===== Seller Name ===== **/
		
		/** ===== Pancard ===== **/

		jQuery(".pan-failed").hide();
		var panregex =/^([a-zA-Z]){5}([0-9]){4}([a-zA-Z]){1}?$/;
		var panVal = jQuery("#pan_no").val();
		if(panVal != "")	{
			jQuery("#advice-required-entry-pan_no").css({
						"opacity": "0",
                        "display": "none"
						});			
		}
		
		if(panVal == "")	{
			jQuery("#pan_no").after('<span class="pan-failed"></span>');
			jQuery("#advice-required-entry-pan_no").css({
			"opacity": "999",
			"display": "block"
			});
		}else if(!panregex.test(panVal)) {
			jQuery("#pan_no").after('<span class="pan-failed">Enter valid pancard number.</span>');
			jQuery("#advice-required-entry-pan_no").css({
			"opacity": "0",
			"display": "none"
			});
			hasError = 1;
		}
		/** ===== Pancard ===== **/
		
		/** ===== VAT Number ===== **/
		jQuery(".vat-failed").hide();
		var vatregex =/^[0-9]{10,11}$/;
		var vatVal = jQuery("#vat_no").val();
		if(vatVal != "")	{
			jQuery("#advice-required-entry-vat_no").css({
						"opacity": "0",
                        "display": "none"
						});			
		}
		if(vatVal == "")	{
			jQuery("#vat_no").after('<span class="vat-failed"></span>');
			jQuery("#advice-required-entry-vat_no").css({
			"opacity": "999",
			"display": "block"
			});
		}else if(!vatregex.test(vatVal)) {
			jQuery("#vat_no").after('<span class="vat-failed">Enter valid vat number.</span>');
			jQuery("#advice-required-entry-vat_no").css({
			"opacity": "0",
			"display": "none"
			});
			hasError = 1;
		}
		/** ===== VAT Number ===== **/
		
			
		/** ===== Mobile Number ===== **/
		jQuery(".phone-failed").hide();
		var phoneReg = /^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[789]\d{9}$/;
		var phoneVal = jQuery("#phone").val();
		if(phoneVal != "")	{
			jQuery("#advice-required-entry-phone").css({
						"opacity": "0",
                        "display": "none"
						});			
		}
	 	if(phoneVal == '') {
			jQuery("#phone").after('<span class="phone-failed"></span>');
			jQuery("#advice-required-entry-phone").css({
			"opacity": "999",
			"display": "block"
			});
		}else if(!phoneReg.test(phoneVal)) {
			jQuery("#phone").after('<span class="phone-failed">Enter valid mobile number.</span>');
			jQuery("#advice-required-entry-phone").css({
			"opacity": "0",
			"display": "none"
			});
						
			hasError = 1;
		}		
		/** ===== Mobile Number ===== **/
		
		
		/** ===== Address 1 ===== **/
		jQuery(".address1-failed").hide();
		var add1regex =/^[a-zA-Z0-9\/\-.,#_ ]+$/i;
		var add1Val = jQuery("#address1").val();
		if(add1Val != "")	{
			jQuery("#advice-required-entry-address1").css({
						"opacity": "0",
                        "display": "none"
						});			
		}
		if(add1Val == "")	{
			jQuery("#address1").after('<span class="address1-failed"></span>');
			jQuery("#advice-required-entry-address1").css({
			"opacity": "999",
			"display": "block"
			});
		}else if(!add1regex.test(add1Val)) {
			jQuery("#address1").after('<span class="address1-failed">Enter valid Address.</span>');
			jQuery("#advice-required-entry-address1").css({
			"opacity": "0",
			"display": "none"
			});
			hasError = 1;
		}
		/** ===== Address 1 ===== **/
		
		
		/** ===== Zip code ===== **/
		jQuery(".zip-failed").hide();
		var zipcodestart= 560000;
		var zipcodeend = 560300;
		var zipcodekVal = jQuery("#pincode").val();
		if(zipcodekVal != "")	{
			jQuery("#advice-required-entry-pincode").css({
						"opacity": "0",
                        "display": "none"
						});			
		}
		if(zipcodekVal == '') {
			jQuery("#pincode").after('<span class="zip-failed"></span>');
			jQuery("#advice-required-entry-pincode").css({
			"opacity": "999",
			"display": "block"
			});
			
		}else if(!(zipcodekVal > zipcodestart && zipcodekVal < zipcodeend)) {
			jQuery("#pincode").after('<span class="zip-failed">Enter only bangalore zip code.</span>');
			jQuery("#advice-required-entry-pincode").css({
			"opacity": "0",
			"display": "none"
			});
			
			hasError = 1;
		}
		/** ===== Zip code ===== **/
	
		
		/** ===== Contact person Name ===== **/
		jQuery(".cperson1-failed").hide();
		var cperson1regex =/^[a-zA-Z ]{1,50}$/;
		var cperson1Val = jQuery("#contact_person_1").val();
		if(cperson1Val != "")	{
			jQuery("#advice-required-entry-contact_person_1").css({
						"opacity": "0",
                        "display": "none"
						});			
		}
		if(cperson1Val == "")	{
			jQuery("#contact_person_1").after('<span class="cperson1-failed"></span>');
			jQuery("#advice-required-entry-contact_person_1").css({
			"opacity": "999",
			"display": "block"
			});
		}else if(!cperson1regex.test(cperson1Val)) {
			jQuery("#contact_person_1").after('<span class="cperson1-failed">Enter valid contact name.</span>');
			jQuery("#advice-required-entry-contact_person_1").css({
			"opacity": "0",
			"display": "none"
			});
			hasError = 1;
		}
		/** ===== Contact person Name ===== **/
		
		
		/** ===== Contact person Name ===== **/
		jQuery(".cperson2-failed").hide();
		var cperson2regex =/^[a-zA-Z ]{1,50}$/;
		var cperson2Val = jQuery("#contact_person_2").val();
		if(cperson2Val != "")	{
			jQuery("#dvice-required-entry-contact_person_2").css({
						"opacity": "0",
                        "display": "none"
						});			
		}
		if(cperson2Val == "")	{
			jQuery("#contact_person_2").after('<span class="cperson2-failed"></span>');
			jQuery("#dvice-required-entry-contact_person_2").css({
			"opacity": "999",
			"display": "block"
			});
		}else if(!cperson2regex.test(cperson2Val)) {
			jQuery("#contact_person_2").after('<span class="cperson2-failed">Enter valid contact name.</span>');
			jQuery("#dvice-required-entry-contact_person_2").css({
			"opacity": "0",
			"display": "none"
			});
			hasError = 1;
		}
		/** ===== Contact person Name ===== **/
		
		
		/** ===== Email ===== **/
		jQuery(".email-failed").hide();
		var emailregex =/^([0-9a-zA-Z\-_.]+@[a-zA-z]{2,7}([\w-]+\.)+[\w-]{2,4})?$/;
		var emailVal = jQuery("#email_id_1").val();
		if(emailVal != "")	{
			jQuery("#advice-required-entry-email_id_1").css({
						"opacity": "0",
                        "display": "none"
						});			
		}
		if(emailVal == "")	{
			jQuery("#email_id_1").after('<span class="email-failed"></span>');
			jQuery("#advice-required-entry-email_id_1").css({
			"opacity": "999",
			"display": "block"
			});
		}else if(!emailregex.test(emailVal)) {
			jQuery("#email_id_1").after('<span class="email-failed">Enter valid email.</span>');
			jQuery("#advice-required-entry-email_id_1").css({
			"opacity": "0",
			"display": "none"
			});
			hasError = 1;
		}
		/** ===== Email ===== **/
		
		
		/** ===== Bank Name ===== **/
		jQuery(".bankname-failed").hide();
		
		var banknameVal = jQuery("#bank_name").val();
		if(banknameVal != "")	{
			jQuery("#advice-required-entry-bank_name").css({
						"opacity": "0",
                        "display": "none"
						});			
		}
		if(banknameVal == "")	{
			jQuery("#bank_name").after('<span class="bankname-failed"></span>');
			jQuery("#advice-required-entry-bank_name").css({
			"opacity": "999",
			"display": "block"
			});
		}
		/** ===== Bank Name ===== **/
		
		
		/** ===== Bank Account Number ===== **/
		jQuery(".bankacc-failed").hide();
		var bankaccregex =/^[0-9]{7,16}$/;
		var bankaccVal = jQuery("#bank_acc").val();
		if(bankaccVal != "")	{
			jQuery("#advice-required-entry-bank_acc").css({
						"opacity": "0",
                        "display": "none"
						});			
		}
		if(bankaccVal == "")	{
			jQuery("#bank_acc").after('<span class="bankacc-failed"></span>');
			jQuery("#advice-required-entry-bank_acc").css({
			"opacity": "999",
			"display": "block"
			});
		}else if(!bankaccregex.test(bankaccVal)) {
			jQuery("#bank_acc").after('<span class="bankacc-failed">Enter valid bank account number.</span>');
			jQuery("#advice-required-entry-bank_acc").css({
			"opacity": "0",
			"display": "none"
			});
			hasError = 1;
			
		}
		/** ===== Bank Account Number ===== **/
		
        if(hasError == 1)
		 {
			return false;
		 }else{
			return true;
		 }
   });
   
   
  // var homepageUrl = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>";
  // var delay = 2000;
   //if (jQuery(".messages")[0]){
   //setTimeout(function(){ window.location = homepageUrl; }, delay);
	//} 
   
});
   
</script>
