<?php
/**
 * Diglin GmbH
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    Diglin
 * @package     Diglin_Username
 * @copyright   Copyright (c) 2008-2015 Diglin GmbH (http://www.diglin.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *
 * Diglin GmbH - change the strings to add 'Username' information
 */
?>
<style>
.forget-msgs .error-msg{ color: #A94442;
	background-color: #F2DEDE;
	padding: 8px;
	margin-bottom: 15px;
	border: 1px solid transparent;float: left;
width: 80%;
	text-align: center;}
.forget-msgs .success-msg{ color: #3C763D;float: left;
width: 80%;
	background-color: #DFF0D8;
	padding: 8px;
	margin-bottom: 15px;
	border: 1px solid transparent;
	text-align: center;}
.forget-msgs{width:48%; 
margin:auto;}
</style>
<div class="catalog-category-view">
    <div class="main container container-sub-content">
        <div class="well-block" style="width: 100%; margin-top: 45px; overflow:hidden;">
<div class="forget-msgs"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
            <div class="page-title">
                <!-- <h1><?php echo $this->__('Forgot Your Password?') ?></h1> -->
            </div>
            
            <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
                
                <div class="forgetcontainer col-lg-6 col-md-9 col-sm-12 col-xs-12" style="margin: 0px auto; float: none;">
                    <h4 class="retrtxt"><?php echo $this->__('Retrieve your password here') ?></h4>
                    <div class="yellowline"></div>
                    <div class="clearfix"></div>
                    <p class="forgetpwdcmt"><?php echo Mage::helper('username')->__('Please enter your Mobile Number below. You will receive a link to reset your password.') ?></p>
                                                     
                    <div class="input-box cinput">
                        <input type="text" name="email" alt="email" id="email_address" maxlength="10" class="input-text required-entry" style="width:80%; margin-bottom:40px;" placeholder="Enter Mobile Number" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
                    </div>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                           
                    <!--<div style="margin-bottom:40px; color:#bf4a32;" ><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>-->
                    <div class="fwdbutton-set">
                        <a title="<?php echo $this->__('Back to Login') ?>" href="<?php echo $this->getUrl('customer/account/create'); ?>" class="back_btn"><?php echo $this->__('Back to Login') ?></a>
                        <button id="form-validat" type="submit" title="<?php echo $this->__('Get My Password') ?>" class="button form-validate fwdbtn">Get My Password</button>
                        
                    </div>
                </div><!-- forgetcontainer end-->
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
<style>.error1{color:red;}.error{color:red;}</style>
<script type="text/javascript">
	jQuery(document).ready(function() {

	jQuery('#form-validat').click(function() { 
	
	jQuery(".error1").hide();
	var hasError1 = false;
	var mobiReg = /^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[789]\d{9}$/;
	//var mobiReg1 = /^(?:[2-9][0-8][0-9])(?!(\d)\1+$)([2-9][0-9]{2}[0-9]{4})$/;
	
	var mobileVal = jQuery("#email_address").val();

    if(mobileVal == '') {
        jQuery("#email_address").after('<span class="error1">Enter Mobile Number.</span>');
        hasError1 = true;
    }

    else if(!mobiReg.test(mobileVal)) {
        jQuery("#email_address").after('<span class="error1">Enter Valid Mobile Number.</span>');
        hasError1 = true;
    }

    if(hasError1 == true) { return false; }

   });
 
});
 </script>
