<?php $_code=$this->getMethodCode() ?>
 <div class="cq_dd_payment">
            <p class="p_text">1. Write a cheque/DD with below given details.</p>
            <div class="pay_box"><span class="name">Pay to/ In Favour of :</span> <span class="details">mSupply</span>
                <span class="name">Date:</span> <span class="details">Today’s Date</span>
                <span class="name">Amount.:</span> <span class="details">662.00</span>
            </div>
            <p class="p_text"><span>Note:</span><b> Post dated cheques are not accepted.</b></p>
            <p class="p_text">2. Enter the details below</p>
        <input type="text" placeholder="*<?php echo $this->__('Demand Draft No#') ?>" title="<?php echo $this->__('Demand Draft No#') ?>" class="input-text required-entry validate-number" id="<?php echo $_code ?>_dd_no" name="payment[dd_no]" value="<?php echo $this->htmlEscape($this->getInfoData('dd_no')) ?>" />
     <!-- <span class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <input class="mydate input-text required-entry" name="payment[dd_date]" value="<?php echo $this->htmlEscape($this->getInfoData('dd_date')) ?>" id="<?php echo $_code ?>_dd_date" placeholder="*<?php echo $this->__('Demand Draft Date(mm/dd/yy):') ?>" title="<?php echo $this->__('Demand Draft Date(mm/dd/yy):') ?>" readonly type="text"> 
        
        <script type="text/javascript">
            
            jQuery(function() {
              jQuery( "#<?php echo $_code ?>_dd_date" ).datepicker({
                minDate: 0 // 0 days offset = today
              });
            });
            
            
            jQuery("#<?php echo $_code ?>_dd_date").on("click", function() {
              jQuery("#<?php echo $_code ?>_dd_date").datepicker("show");
            });
                      
        </script>
      </span>

      <span class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <input type="text"  placeholder="*<?php echo $this->__('Drawee Name') ?>" title="<?php echo $this->__('Drawee Name') ?>" class="input-text required-entry" id="<?php echo $_code ?>_draweenamedd" name="payment[draweenamedd]" value="<?php echo $this->htmlEscape($this->getInfoData('draweenamedd')) ?>" />
      </span>
-->
        <input type="text"  placeholder="*<?php echo $this->__('Drawee Bank') ?>" title="<?php echo $this->__('Drawee Bank') ?>" class="input-text required-entry" id="<?php echo $_code ?>_draweebankdd" name="payment[draweebankdd]" value="<?php echo $this->htmlEscape($this->getInfoData('draweebankdd')) ?>" />


      <!-- <div class="our-dd">
      <div class="our-dd-local">
      <input class="radio" type="radio" id="<?php echo $_code ?>_cheqlocdd" name="payment[cheqlocdd]" value="1" /> <span>Local DD</span><br>
      </div>
      <div class="our-dd-out">
      <input class="radio" type="radio" id="<?php echo $_code ?>_cheqlocdd" name="payment[cheqlocdd]" value="2" /> <span>Outstation DD</span>
      </div>
      </div> -->
      <!-- <div class="input-box">

      <span class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <input type="text"  placeholder="*<?php echo $this->__('PAN Number ') ?>" title="<?php echo $this->__('PAN Number ') ?>" class="input-text required-entry" id="<?php echo $_code ?>_pannodd" name="payment[pannodd]" value="<?php echo $this->htmlEscape($this->getInfoData('pannodd')) ?>" />
      </span>
      </div> -->
      <?php echo $this->getMethod()->getConfigData('message');?>
<div class="btn_wrapper">
                <div class="trms-cndts"> By placing the order, I have read and agreed to msupply.com <br/> <span class="terms-conditions"> Terms Use | Terms of Sale </span></div>
            </div>
</div>
