<!--mSupply Service Providers start-->
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <div class="container">
    <div class="row">
      <div class="service">
          <h1>mSupply Service Providers</h1>
            <div class="col-lg-6 col-xs-12 pad0"><img src="<?php echo $this->getSkinUrl('images/service_01.jpg'); ?>" alt=""></div>
            <div class="col-lg-6 col-xs-12 pad0">
              <div class="service_box">
                <h4 class="black">Are you an architect or Interior designer?</h4>
                <h4>Many customers are looking for you.</h4>
				<form id="serviceproviderForm1" action="<?php echo $this->getUrl('serviceproviders/index/save'); ?>" method="post">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><input type="text" placeholder="Name" name="name" id="name" /></div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><input type="text" placeholder="Phone" name="phone" id="phone" /></div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                  <select title="interior" name="service" id="service" >
				    <option value="">Please Select</option>
                    <option value="Architect">Architect</option>
                    <option value="Interior Designer">Interior Designer</option>
                  </select>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"><button type="submit" class="know_more_btn">Register</button></div>
				</form>
              </div>
          </div>
          <div class="clearfix"></div>
            <div class="col-lg-6 col-lg-12 pad0">
              <div class="service_box-2">
                <h4 class="black">Are you a contractor, plumber, electrician or carpenter ?</h4>
                <h4>Our customers want your services.</h4>
				<form id="serviceproviderForm2" action="<?php echo $this->getUrl('serviceproviders/index/save'); ?>" method="post">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><input type="text" placeholder="Name" name="name" id="name" /></div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12"><input type="text" placeholder="Phone" name="phone" id="phone" /></div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                  <select title="interior" name="service" id="service" >
				    <option value="">Please Select</option>
                    <option value="Contractor">Contractor</option>
                    <option value="Plumber">Plumber</option>
                    <option value="Electrician">Electrician</option>
                    <option value="Carpentor">Carpentor</option>
                    <option value="Painter">Painter</option>
                  </select>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12"><button type="submit" class="know_more_btn">Register</button></div>
				</form>
              </div>
            </div>
            <div class="col-lg-6 col-lg-6 col-lg-6 col-lg-12 pad0"><img src="<?php echo $this->getSkinUrl('images/service_02.jpg'); ?>" alt=""></div>

      </div>
    </div>
  </div>
</div>
<!--mSupply Service Providers end-->