<div class="fixed-navbar-block">
  <!-- Fixed navbar -->
  <div class="navbar navbar-default navbar-fixed-top col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="col-lg-3 col-md-3 col-sm-4 col-xs-8">
      <!-- inner page menu start -->
      <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('inner-page-menu')->toHtml();?>
	  <div class="width85" id="mainLogo"> 
		<a href="<?php echo $this->getUrl(); ?>" class="pull-left tag-block"> 
			<img title="Building, Construction & Interior Materials Online" alt="Building, Construction & Interior Materials Online" src="<?php echo $this->getSkinUrl('images/mSupply-logo-revised.svg'); ?>" class="logo-svg img-responsive" />
			<img title="Building, Construction & Interior Materials Online" alt="Building, Construction & Interior Materials Online" src="<?php echo $this->getSkinUrl('images/mSupply-logo-revised.png'); ?>" class="logo-svg1 img-responsive" />
		</a>
      </div>
    </div>
	<div class="col-lg-5 col-md-4 col-sm-4 col-xs-4 search-icon mobile-display "><button type="submit" title="<?php echo $this->__('Search') ?>" class="button search-button"><i class="fa fa-search"></i></button></div>
    <div class="col-lg-5 col-md-4 col-sm-4 col-xs-12 search-block" id="serch"><?php echo $this->getChildHtml('topSearch') ?> </div>
    <div class="col-lg-4 col-md-5 col-sm-4 col-xs-0 account-info-header">
      <ul class="nav navbar-nav navbar-brand">
        <li id="lnkConnect" class="border-bottom desktop-display"> 
		<a href="#"><i class="fa fa-phone fa-fw"></i> <span class="helptext"><?php echo Mage::getStoreConfig('configuration/configuration_header_telephone/headerphonenumber'); ?></span></a>
		  <div class="popup-block" id="divConnect">
            <ul>
              <li>
                <label><?php echo Mage::getStoreConfig('configuration/configuration_header_telephone/headerphonenumber'); ?></label>
              </li>
            </ul>
          </div>
		
		</li>
        <li class="border-bottom desktop-display place"> <a href="#"><i class="fa fa-map-marker fa-fw"></i><span class="helptext">Bangalore</span> </a>
          <div class="popup-block" id="divLocation">
            <ul>
              <li>Bangalore</li>
            </ul>
          </div>
        </li>      
        <li id="lnkAccount" class="border-bottom"> <a href="#"><i class="fa fa-user fa-fw"></i><span class="helptext acct">Account</span></a>
          <?php if(!Mage::getSingleton( 'customer/session')->isLoggedIn()) { ?>
          <div class="popup-block" id="divAccount">
            <ul>
              <li><i class="fa fa-user"></i>
               <a href="<?php echo $this->getUrl('customer/account/login'); ?>" class="lnkLookBtn">Login</a>
              </li>
              <li>
                <label>New User? <a href="<?php echo $this->getUrl('customer/account/create'); ?>">Sign Up</a> </label>
              </li>
            </ul>
          </div>
          <?php } else { ?>
          <div class="popup-block text-center" id="divLoggedUser">
            <ul>
              <li><i class="fa fa-user fa-fw"></i>Hello, <span id="firstName"><?php echo $this->__(Mage::getSingleton('customer/session')->getCustomer()->getFirstname()); ?></span> </li>
              <li><a href="<?php echo $this->getUrl('customer/account/create'); ?>">My Account</a> </li>
              <li><a href="<?php echo $this->getUrl('sales/order/history'); ?>">My Orders</a> </li>
              <li><a href="<?php echo $this->getUrl('wishlist'); ?>">My Wishlist</a> </li>
              <li>
                <button type="button" id="btnLogout">Logout</button>
              </li>
            </ul>
          </div>
          <?php } ?> </li>
        <li class="border-bottom cart-block"> <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><i class="fa fa-shopping-cart fa-fw"></i>
              <span class="helptext">Shopping List</span>
        <?php $cartcount = Mage::helper('checkout/cart')->getCart()->getItemsCount(); if($cartcount >0){ ?>
        <span class="carcount"><?php echo $cartcount;?></span>
        <?php }?>
          </a> </li>
        </ul>        
      </div>
    </div>
</div>
<script type="text/javascript">
  jQuery("#btnLogin").click(function() {
    window.location.href = "<?php echo $this->getUrl('customer/account/create'); ?>";
  });
  jQuery("#btnLogout").click(function() {
    window.location.href = "<?php echo $this->getUrl('customer/account/logout'); ?>";
  });
</script>
<?php if(Mage::getBlockSingleton( 'page/html_header')->getIsHomePage()) { ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('new-home-popup')->toHtml();?>
<?php } ?>

<div class="col-xs-12 account-fixed-header mobile-display">
  <ul class="nav navbar-nav navbar-brand">
	<li id="lnkConnect"> <a  data-toggle="modal" data-target="#contactPopup"><i class="fa fa-phone fa-fw"></i></a>
	</li>
	<?php if(!Mage::getSingleton( 'customer/session')->isLoggedIn()) { ?>	
		<li id="lnkAccount"> <a href="<?php echo $this->getUrl('customer/account/login'); ?>"><i class="fa fa-user fa-fw"></i></a>
		</li>	
    <?php } else { ?>
		<li id="lnkAccount1"> <a href="<?php echo $this->getUrl('logout_mobile_content'); ?>"><i class="fa fa-user fa-fw"></i></a>
		</li>	
	  <?php } ?>



	<li class="cart-block"> <a href="<?php echo $this->getUrl('checkout/cart'); ?>"><i class="fa fa-shopping-cart fa-fw"></i>
		  <span class="helptext">Shopping List</span>
	<?php $cartcount = Mage::helper('checkout/cart')->getCart()->getItemsCount(); if($cartcount >0){ ?>
	<span class="carcount"><?php echo $cartcount;?></span>
	<?php }?>
	  </a> </li>
	</ul>        
  </div>
  
  


  
  <div class="modal fade" id="contactPopup" role="dialog">
    <div class="modal-dialog">
		<div class="modal-content">			
			<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel">Contact Us</h4>
			  <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>	
			
			</div>
			<ul class="modal-contact">
				<li><i class="fa fa-phone"></i><?php echo Mage::getStoreConfig('configuration/configuration_header_telephone/headerphonenumber'); ?></li>
				<li><i class="fa fa-location-arrow"></i><a href="mailto:support@msupply.com">support@msupply.com</a></li>
				<li><span>Hours of Operation: 7:00 a.m. to 10:00 p.m.<br>
					Monday to Saturday</span><br></li>
			</ul>
		</div>
    </div>
  </div>
   