<?php
/**
 * Diglin GmbH
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    Diglin
 * @package     Diglin_Username
 * @copyright   Copyright (c) 2008-2015 Diglin GmbH (http://www.diglin.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

$customer = Mage::getSingleton('customer/session')->getCustomer();
?>
<?php if ($customer->getUsername()):?>
<!--<div class="col2-set">
    <div class="box">

        <div class="box-content">
            <div class="col-1">
                
                <div class="box-title">
                    <h3><?php echo $this->__('ADDITIONAL INFORMATION') ?></h3>
                    <a href="<?php echo $this->getUrl('customer/account/edit') ?>"><?php echo $this->__('Edit') ?></a>
                </div>
                <div class="box-content">
                     <p>
                        <?php echo $this->__('User Id: ') . $this->escapeHtml($customer->getUsername()) ?>
                    </p>
                </div>

            </div>-->

<?php endif; ?>