<?php $_code=$this->getMethodCode() ?>

<div class="cash_payment" style="display:none; width:100% !important;" id="payment_form_<?php echo $_code ?>">
                <!--<p class="p_text"><b>CBD (Cash Before Dispatch)</b><br/>
                Available only on purchase above &#8377;10,000 per transaction</p>-->
                <p class="p_text" style="margin-bottom:50px;"><b>Cash On Delivery (COD)</b><br/>
				<span style="color: #637078;float: left;margin: 10px 0 !important;padding: 0;width: 100%;">Cash on Delivery is applicable only for orders above &#8377;1,000</span><br/>
                <!--To avail this option please contact us at <b>+91-7899901156</b> or <b>support@msupply.com</b>--></p>
				
				<?php 
				if(Mage::getSingleton('customer/session')->isLoggedIn()) 
				{
			        $customerData = Mage::getSingleton('customer/session')->getCustomer();
				    $cusId = $customerData->getId();
					$customer = Mage::getModel('customer/customer')->load($cusId); 
                    $panNo = $customer->getPanNumber();
				} 
				?>
				
				<?php if(!$panNo) { ?>
				<div id="pan_block">
					<p class="pantext">Enter PAN Number</p>
					<div class="col-lg-5 col-sm-8 col-md-5 col-xs-12 mb10">	
					<input type="text" placeholder="*PAN Number" title="PAN Number" class="input-text required-entry panno" id="<?php echo $_code ?>_panno" name="payment[panno]" value="<?php echo $panNo; ?>" maxlength="10" />
					</div>
				</div>
				<?php } else { ?>
				<div class="col-lg-5 col-sm-8 col-md-5 col-xs-12 mb10">	
					<input type="hidden" placeholder="*PAN Number" title="PAN Number" class="input-text required-entry panno" id="<?php echo $_code ?>_panno" name="payment[panno]" value="<?php echo $panNo; ?>" maxlength="10" />
				</div>
				<?php } ?>
				
				<div class="clear"></div>
				<div class="btn_wrapper_new">
				<div class="buttons-set allinonebtn"  id="payment_form_<?php echo $_code ?>">
				<div  class="buttons-set" id="payment-buttons-container">
				
				<button type="button" class="button" id="payment_submit"><span><?php echo $this->__('Continue') ?></span></button>
				
				<span class="please-wait loader-pay<?php echo $_code ?>" id="payment-please-wait" style="display:none;">
				<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Please Wait...') ?>" title="<?php echo $this->__('Please Wait...') ?>" class="v-middle" /> <?php echo $this->__('Please Wait...') ?>
				</span>
				</div>
				<div class="trms-cndts"> By placing the order, I have read and agreed to mSupply.com <br/> <span class="terms-conditions"><a href="<?php echo $this->getUrl('terms_and_conditions'); ?>" target="__blank"> Terms of Use | Terms of Sale</a> </span></div>
				</div>
				</div>
            </div>
		</div>
   
   <div>
      <?php echo $this->getMethod()->getConfigData('message');?>
   </div>


<script type="text/javascript"> 
 
jQuery(document).ready(function() {
	jQuery('#payment_submit').click(function() {
		jQuery(".pan-failed").hide();
		var hasError = 0;
		var panregex =/^([a-zA-Z]){5}([0-9]){4}([a-zA-Z]){1}?$/;
		var panVal = jQuery("#<?php echo $_code ?>_panno").val();
		if(panVal == "")	{
			jQuery("#<?php echo $_code ?>_panno").after('<span class="pan-failed"></span>');
			jQuery("#advice-required-entry-cashin_panno").css({
			"opacity": "999",
			"display": "block"
			});
		}else if(!panregex.test(panVal)) {
			jQuery("#<?php echo $_code ?>_panno").after('<span class="pan-failed" style="color:#cc3300;">Enter valid pancard number.</span>');
			jQuery("#advice-required-entry-cashin_panno").css({
			"opacity": "0",
			"display": "none"
			});
			hasError = 1;
		}
		
		 if(hasError == 1)
		 {
			return false;
		 }else{
			loader('<?php echo $_code ?>');payment.save();
		 }
		
	});
});	
		/** ===== Pancard ===== **/
 </script>		