<?php
/**
 * Diglin GmbH
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    Diglin
 * @package     Diglin_Username
 * @copyright   Copyright (c) 2008-2015 Diglin GmbH (http://www.diglin.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
 ?>
 <!--
<div class="page-title">
    <h1><?php echo $this->__('Edit Account Information') ?></h1>
</div>-->
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
     <span class="my-account-heading"><?php echo $this->__('Account Information') ?></span>
    <div class="text_fild">
        <?php echo $this->getBlockHtml('formkey')?>
        <ul>
             <li class="fields">
                <label>User Id: </label> <?php echo $this->escapeHtml($this->getCustomer()->getUsername()) ?>
            </li>
            <li class="fields">
                <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?>
            </li>
            <li>
            	<div class="input-box" >
                <input type="text" placeholder="* Email" name="email" id="email" value="<?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text required-entry" />
                </div>
            </li>      



            <!-- New Requirement Start -->
	                    <li>
						<div class="input-box">        
						<?php 
						  $attributePrimary = Mage::getModel('eav/config')->getAttribute('customer', 'primary_select');
						  $allOptionsPrimary = $attributePrimary->getSource()->getAllOptions(true, true); 
						  
						  $currentPrimary = $this->escapeHtml($this->getCustomer()->getPrimarySelect());
						?>
						<select id="primary_select" name="primary_select" value="<?php echo $this->escapeHtml($this->getCustomer()->getPrimarySelect()) ?>" class="validate-select">
							<option value="">Primarily, I am a .. (Select One)</option>
							<?php foreach ($allOptionsPrimary as $instancePrimary): ?>
							<?php if($instancePrimary['value']){ ?>
							<option value="<?php echo $instancePrimary['value']; ?>" <?php if($currentPrimary == $instancePrimary['value']): ?>selected="selected"<?php endif; ?>><?php echo $instancePrimary['label']; ?></option>
							<?php } ?>
							<?php endforeach; ?>
							</select>
						</div>
						</li>
						
                         <li class="secondary_select_hole" style="margin-top:15px;">
                        <div class="input-box">
                        <?php 
                          $attributeSecondary = Mage::getModel('eav/config')->getAttribute('customer', 'secondary_select');
                          $allOptionsSecondary = $attributeSecondary->getSource()->getAllOptions(true, true); 
                          $lastItem = end($allOptionsSecondary);
						  
						  $currentSecondary = $this->escapeHtml($this->getCustomer()->getSecondarySelect());
                        ?>
						 <dl class="dropdown-selection"> 
							<dt>
							<a>                                   
							  <p class="multiSel"><span class="hida">I am also .. (Select Multiple)</span> </p>  
							</a>
							</dt>  
							<dd>
								<div class="mutliSelect">
									<ul>
									    <?php foreach ($allOptionsSecondary as $instanceSecondary): ?>
                                        <?php if($instanceSecondary['value']){ ?>
										<li><label><input type="checkbox" id="<?php echo $instanceSecondary['label']; ?>" name="secondary[]" data-val="<?php echo $instanceSecondary['label']; ?>" value="<?php echo $instanceSecondary['value']; ?>" <?php if(strpos($currentSecondary, $instanceSecondary['value']) !== false): ?>checked="checked"<?php endif; ?> /><?php echo $instanceSecondary['label']; ?></label></li>
										<?php } ?>
                                        <?php endforeach; ?>
									</ul>
								</div>
							</dd>
						</dl> 
						<input type="hidden" name="secondary_select" id="secondary_select" value="<?php echo $this->escapeHtml($this->getCustomer()->getSecondarySelect()) ?>" />
                        </div>   
                        </li>
						
                        <li>						
						<div class="input-box" id="builderSelect" style="display:none;">
							<input type="text" placeholder="Name of builder Company" name="builder_company" id="builder_company" value="<?php echo $this->escapeHtml($this->getCustomer()->getBuilderCompany()) ?>" class="input-text" />
						</div>
						</li>
						
						<li>                        
                        <div class="input-box" id="otherSelect" style="display:none;">
                            <input type="text" placeholder="Others" name="others_customer" id="others_customer" value="<?php echo $this->escapeHtml($this->getCustomer()->getOthersCustomer()) ?>" class="input-text" />
                        </div>
                        </li>
						
						<script>
						
						jQuery("input:checkbox").each(function() {
						if (jQuery(this).is(":checked")) {
						var selectedSeondary = jQuery(this).attr("id");
						var html = '<span title="' + selectedSeondary + '">' + selectedSeondary + '</span>';
                        jQuery('.multiSel').append(html);
                        jQuery(".hida").hide();
						}
						});
						
		
						var builderCompany = jQuery('#builder_company').val();
						if(builderCompany != '')
						{
						jQuery('#builderSelect').css('display','block');	
						}
                        else
                        {
						jQuery('#builderSelect').css('display','none');	
						}
						
						
						
						var otherCustomer = jQuery('#others_customer').val();
						if(otherCustomer != '')
						{
						jQuery('.secondary_select_hole').css('display','none');		
						jQuery('#otherSelect').css('display','block');	
						}
                        else
                        {
						jQuery('.secondary_select_hole').css('display','block');		
						jQuery('#otherSelect').css('display','none');	
						}
						
						
						//Primary Select Start
						jQuery('#primary_select').on('change', function() {
                        var selectedPrimary = jQuery('#primary_select option:selected').text();
						
						//Builder Check
						if(selectedPrimary == 'Builder')
						{
						jQuery('#builderSelect').css('display','block');
                        jQuery('#builder_company').addClass('required-entry');						
						}
                        else
						{
							
						jQuery('#builderSelect').css('display','none');	
						if(!jQuery('#Builder').is(":checked"))
						{
						jQuery('#builder_company').removeClass('required-entry');
						jQuery('#builder_company').val('');	
                        }   						
						}
						
						//Other Check
						if(selectedPrimary == 'Others')
                        {
						jQuery('.secondary_select_hole').css('display','none');	
                        jQuery('#otherSelect').css('display','block');
                        jQuery('#others_customer').addClass('required-entry');
						jQuery('#Builder').prop('checked', false);
						jQuery('#builder_company').val('');
						jQuery('#builderSelect').css('display','none'); 
						jQuery('#builder_company').removeClass('required-entry');
		
                        }
                        else
                        {
						jQuery('.secondary_select_hole').css('display','block');	
                        jQuery('#otherSelect').css('display','none'); 
                        jQuery('#others_customer').removeClass('required-entry');
						jQuery('#others_customer').val('');
                        }

						//Call Secondary
                        if(jQuery('#Builder').is(":checked"))
						{
						jQuery('#builderSelect').css('display','block'); 
						}
						
						
                        })
						//Primary Select End
						
						//Secondary Select Start
                        jQuery(".mutliSelect ul").click(function(){
                        var output = jQuery.map(jQuery(':checkbox[name=secondary\\[\\]]:checked'), function (n, i) {
						return n.value;
						}).join(',');
						jQuery('#secondary_select').val(output);
                        
						//Builder Check
						if(jQuery('#Builder').is(":checked"))
						{
						jQuery('#builderSelect').css('display','block'); 
						jQuery('#builder_company').addClass('required-entry');	
						}
						else
						{
						jQuery('#builderSelect').css('display','none'); 
						var selectedPrimaryNew = jQuery('#primary_select option:selected').text();
						if(selectedPrimaryNew != 'Builder')
						{
						jQuery('#builder_company').removeClass('required-entry');
						jQuery('#builder_company').val('');
						}
						}
						
						//Other Check
						if(jQuery('#Others').is(":checked"))
						{
						jQuery('#otherSelect').css('display','block'); 
						jQuery('#others_customer').addClass('required-entry');
						jQuery('#builder_company').val('');
						jQuery('#builderSelect').css('display','none'); 
						jQuery('#builder_company').removeClass('required-entry');
						}
						else
						{
						jQuery('#otherSelect').css('display','none'); 
						jQuery('#others_customer').removeClass('required-entry');
						jQuery('#others_customer').val('');
						}
						
						
                        //Call Primary
                        var selectedPrimary = jQuery('#primary_select option:selected').text();
                        if(selectedPrimary == 'Builder')
                        {
                        jQuery('#builderSelect').css('display','block');    
                        }
						
						
                        
                        });
                        //Secondary Select End
						</script>
               
                    <!-- New Requirement End -->





			
           <!-- <li>
                <div class="field name-lastname">
                    <div class="input-box">
                    <?php if(Mage::getStoreConfigFlag('username/general/frontend')) : ?>
           <input type="text" name="username" id="username" value="<?php echo $this->escapeHtml($this->getCustomer()->getUsername()) ?>" title="<?php echo Mage::helper('customer')->__('Username') ?>" class="input-text required-entry" />
                    <?php else: ?>
                        <input type="text" name="username" id="username" value="<?php echo $this->escapeHtml($this->getCustomer()->getUsername()) ?>"/>
                        <?php //echo $this->escapeHtml($this->getCustomer()->getUsername()); ?>
                    <?php endif;?>
                    </div>
                </div>

              </li>
			  <li class="right">
					<input type="text" name="mobile_code" id="mobile_code" value="<?php echo $this->htmlEscape($code) ?>" title="<?php echo $this->__('Country Code') ?>" class="input-text validate-digits validate-number" style="width:38px;" />              
                        <input type="text" placeholder="Mobile No." name="mobile" id="mobile" value="<?php echo $this->htmlEscape($mob) ?>" title="<?php echo $this->__('Mobile No.') ?>" class="input-text validate-digits validate-number" style="width:85%; float:right;" /><br />
              </li>-->
             <div class="clearfix"></div>
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
        <?php endif ?>
        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
        <?php endif ?>
        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <li><?php echo $_gender->setGender($this->getCustomer()->getGender())->toHtml() ?></li>
        <?php endif ?>
            <li class="control">
                <input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="change_password"><?php echo $this->__('Change Password') ?></label>
            </li>
        </ul>
    </div>
    <div class="fieldset" style="display:none;">
        <div class="block-title"><!--<?php echo $this->__('Change Password') ?>--></div>
        <ul>
            <li>
                <div class="input-box">
                    <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                    <input type="text" class="input-text no-display hide" name="dummy" id="dummy" />
                    <input type="password" placeholder="* Current Password" title="<?php echo $this->__('Current Password') ?>" class="input-text" name="current_password" id="current_password" />
                </div>
            </li>
            <li class="fields">
                <div class="input-box">
                    <input type="password" placeholder="* New Password" title="<?php echo $this->__('New Password') ?>" class="input-text validate-password" name="password" id="password" />
                </div>
            </li>
            <li>
                <div class="input-box">
                    <input type="password" placeholder="* Confirm New Password" title="<?php echo $this->__('Confirm New Password') ?>" class="input-text validate-cpassword" name="confirmation" id="confirmation" />
                </div>
            </li>
            <li>
                
                
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="button"><span><?php echo $this->__('Save') ?></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>

<style>
.multiSel span{background: #ccc none repeat scroll 0 0;border-radius: 5px;float: left;margin: 2px;padding: 5px;}
.hida {background: rgba(0, 0, 0, 0) none repeat scroll 0 0 !important;}
</style>