

<?php $_product = $this->getProduct(); ?>

<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>

<?php if(Mage::helper('customer')->isLoggedIn()) { ?>
		<?php if ( $this->helper('wishlist')->isAllow() ) : ?>
		<a class="pointer" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl(Mage::registry('current_product'));?>')" rel="noindex, nofollow" title="Add to wishlist"><span class="glyphicon glyphicon-heart"></span></a>
		<?php endif; ?>
<?php }else{ ?>
<!--<a href="<?php echo Mage::getUrl('customer/account/create'); ?>" rel="noindex, nofollow" title="Add to wishlist"><span class="glyphicon glyphicon-heart"></span></a>-->
<?php
	}
	?>
	
<?php
    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
?>
<?php if($_compareUrl) : ?>
    <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a>
<?php endif; ?>			


<script>
jQuery('.link-compare').click(function(e){
e.preventDefault();
var url = jQuery(this).attr("href");
jQuery(this).parent().html("Please wait...");
window.location = url;					
})
</script>	
