<?php $_code=$this->getMethodCode() ?>

<div>
<ul class="form-list col-lg-12 col-md-12 col-sm-12 col-xs-12 pad10" id="payment_form_<?php echo $_code ?>" style="display:none; width:100% !important;">

	  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div>
        
        <span>
            <input type="text" placeholder="*<?php echo $this->__('Demand Draft No#') ?>" title="<?php echo $this->__('Demand Draft No#') ?>" class="input-text required-entry validate-number" id="<?php echo $_code ?>_dd_no" name="payment[dd_no]" value="<?php echo $this->htmlEscape($this->getInfoData('dd_no')) ?>" />
        </span>
    </div></div>

    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div>
       
        <span>
		<input class="mydate required-entry" name="payment[dd_date]" value="<?php echo $this->htmlEscape($this->getInfoData('dd_date')) ?>" id="<?php echo $_code ?>_dd_date" placeholder="*<?php echo $this->__('Demand Draft Date(mm/dd/yy):') ?>" title="<?php echo $this->__('Demand Draft Date(mm/dd/yy):') ?>" type="text" readonly />
            <script type="text/javascript">
		
    jQuery(function() {
		jQuery( "#<?php echo $_code ?>_dd_date" ).datepicker({
		  showOn: "button",
		  buttonImage: "<?php echo Mage::getBaseUrl('skin')?>adminhtml/default/default/images/grid-cal.gif",
		  buttonImageOnly: true,
		  buttonText: "Select date",
		   minDate: 0 // 0 days offset = today
		});
    });


	jQuery("#<?php echo $_code ?>_dd_date").on("click", function() {
		jQuery("#<?php echo $_code ?>_dd_date").datepicker("show");
	});
	
	
			
            </script>
        </span>

    </div></div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div>
       
        <span>
            <input type="text"  placeholder="*<?php echo $this->__('Drawee Name') ?>" title="<?php echo $this->__('Drawee Name') ?>" class="input-text required-entry" id="<?php echo $_code ?>_draweenamedd" name="payment[draweenamedd]" value="<?php echo $this->htmlEscape($this->getInfoData('draweenamedd')) ?>" />
        </span>
    </div></div>
  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <div>
                <span>
            <input type="text"  placeholder="*<?php echo $this->__('Drawee Bank') ?>" title="<?php echo $this->__('Drawee Bank') ?>" class="input-text required-entry" id="<?php echo $_code ?>_draweebankdd" name="payment[draweebankdd]" value="<?php echo $this->htmlEscape($this->getInfoData('draweebankdd')) ?>" />
        </span>
    </div></div>
 <!-- <div class="our-dd">
		<div class="our-dd-local">
		
			<input class="radio" type="radio" id="<?php echo $_code ?>_cheqlocdd" name="payment[cheqlocdd]" value="1" /> <span>Local DD</span><br>
	  
		</div>
	    <div class="our-dd-out">
		
			<input class="radio" type="radio" id="<?php echo $_code ?>_cheqlocdd" name="payment[cheqlocdd]" value="2" /> <span>Outstation DD</span>
	  
		</div>
				
	
	</div> -->
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="input-box">
        
        <span>
            <input type="text"  placeholder="*<?php echo $this->__('PAN Number ') ?>" title="<?php echo $this->__('PAN Number ') ?>" class="input-text required-entry" id="<?php echo $_code ?>_pannodd" name="payment[pannodd]" value="<?php echo $this->htmlEscape($this->getInfoData('pannodd')) ?>" />
        </span>
    </div></div>
	
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
</div>