<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
<?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_products as $_product): ?>
    <?php  
	   $_proId = $_product->getId();
	   
	   $produ = Mage::getModel('catalog/product')->load($_proId);
	   $cats = $produ->getCategoryIds();
	   
	   foreach ($cats as $category_id) :
			$_cat = Mage::getModel('catalog/category')->setStoreId(Mage::app()->getStore()->getId())->load($category_id);
			$_catId = $_cat->getId();             
		
	    $store = Mage::app()->getStore();
	    $path = Mage::getResourceModel('core/url_rewrite')
	     ->getRequestPathByIdPath("product/$_proId/$_catId", $store);
	    $url = $store->getBaseUrl($store::URL_TYPE_WEB) . $path;
	?>
	
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="Recently_Viewed row list_produtcs">
            <div class="block-title">
                <h1 class="current-product recent-viewd fade-line"><?php echo $this->__('Your Recently Viewed') ?></h1>
            </div>
        <?php endif; ?>
            <li class="<?php if(($i-1)%$_columnCount==0): ?> <?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> col-lg-2 col-md-2 col-sm-2 col-xs-4 divider">
                <a href="<?php echo $url ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img width="125px" class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(125) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                <div><a href="<?php echo $url ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></div>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php echo $this->getPriceHtml($_product, true, '-home-viewed') ?>
               
            </li>
        <?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
        </ul>
        <?php endif; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>
