<?php $_code=$this->getMethodCode() ?>


   <ul class="form-list col-lg-12 col-md-12 col-sm-12 col-xs-12 pad10" id="payment_form_<?php echo $_code ?>" style="display:none;">
   
   
			<div class="neft_payment">
			<p class="p_text">1. Add mSupply as payee with below given details.</p>
			 
          <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('neft-payment-content')->toHtml(); ?>
			
			<p class="p_text" style="margin:0 10px !important;">2. Make payment.</p>
			<p class="p_text">3. Enter Transaction Id provided by the bank.
			<input type="text" placeholder="<?php echo $this->__('Transaction Id') ?>" title="<?php echo $this->__('Transaction Id') ?>" class="input-text neft-input" id="<?php echo $_code ?>_transaction_id" name="payment[transaction_id]" value="<?php echo $this->htmlEscape($this->getInfoData('transaction_id')) ?>" />
			</p>
			<div class="btn_wrapper_new12">
		<div class="buttons-set allinonebtn12"  id="payment_form_<?php echo $_code ?>">
			<div  class="buttons-set" id="payment-buttons-container">
				<button type="button" class="button" onclick="loader('<?php echo $_code ?>');payment.save();"><span><?php echo $this->__('Continue') ?></span></button>

				<span class="please-wait loader-pay<?php echo $_code ?>" id="payment-please-wait" style="display:none;">
				<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Please Wait...') ?>" title="<?php echo $this->__('Please Wait...') ?>" class="v-middle" /> <?php echo $this->__('Please Wait...') ?>
				</span>
			</div>
			<div class="trms-cndts"> By placing the order, I have read and agreed to mSupply.com <br/> <span class="terms-conditions"><a href="<?php echo $this->getUrl('terms_and_conditions'); ?>" target="__blank"> Terms of Use | Terms of Sale</a> </span></div>
		</div>
		</div>
     
			</div>

      
    </ul>
    <div>
      <?php echo $this->getMethod()->getConfigData('message');?>
    </div>



