<?php
/**
 * Created by Magentix
 * Based on Module from "Excellence Technologies" (excellencetechnologies.in)
 *
 * @category   Magentix
 * @package    Magentix_Convenienceservice
 * @author     Matthieu Vion (http://www.magentix.fr)
 * @license    This work is free software, you can redistribute it and/or modify it
 */
?>

<?php if($this->getSource() instanceof Mage_Sales_Model_Order): ?>

    <?php if ((float)$this->getSource()->getConvenienceserviceAmountRefunded() > 0): ?>
        <tr>
            <td class="label"><strong><?php echo Mage::helper('convenienceservice')->__('Convenienceservice refunded to customer') ?></strong></td>
            <td><strong><?php echo $this->getSource()->getConvenienceserviceAmountRefunded(); ?></strong></td>
        </tr>
    <?php endif; ?>

<?php else: ?>

    <?php if ((float)$this->getSource()->getConvenienceserviceAmount()): ?>
        <tr>
            <td class="label"><strong><?php echo Mage::helper('convenienceservice')->__('Convenienceservice Refunded') ?></strong></td>
            <td><strong><?php echo $this->getSource()->getConvenienceserviceAmount(); ?></strong></td>
        </tr>
    <?php endif;  ?>

<?php endif; ?>

