<?php
/**
 * Created by Magentix
 * Based on Module from "Excellence Technologies" (excellencetechnologies.in)
 *
 * @category   Magentix
 * @package    Magentix_Convenienceservice
 * @author     Matthieu Vion (http://www.magentix.fr)
 * @license    This work is free software, you can redistribute it and/or modify it
 */
?>

<?php $this->setPriceDataObject($this->getSource()) ?>

<?php if ((float) $this->getSource()->getConvenienceserviceAmount()): ?>
    <tr>
        <td class="label"><?php $convenienceservicechargepercentage = Mage::getStoreConfig('convenience/convenience_group/convenienceservicechargepercentage');
		
			echo Mage::helper('convenienceservice')->__("Service Tax ($convenienceservicechargepercentage% of Conv. Fee)") 
		
		?></td>
        <td>
            <?php echo $this->displayPrices($this->getSource()->getBaseConvenienceserviceAmount(), $this->getSource()->getConvenienceserviceAmount()); ?>
        </td>
    </tr>
<?php endif; ?>