<!--<script type="text/javascript" src="<?php echo $this->getJsUrl('lib/ccard.js')  ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('scriptaculous/builder.js')  ?>"></script>-->
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/js.js')  ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/form.js')  ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/menu.js')  ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('mage/translate.js')  ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('mage/cookies.js')  ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/product.js')  ?>"></script>
<!--<script type="text/javascript" src="<?php echo $this->getJsUrl('calendar/calendar.js')  ?>"></script>
<script type="text/javascript" src="<?php echo $this->getJsUrl('calendar/calendar-setup.js')  ?>"></script>-->

<!-- New Home Page -->
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/bootstrap.min.js')  ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/flexy-menu.js')  ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/owl.carousel.js')  ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/new_home.js')  ?>"></script>
<!-- New Home Page End -->
