<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2008-2015 Diglin GmbH - Switzerland (http://www.diglin.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * Create account form template
 *
 * @see app/design/frontend/base/default/template/customer/form/register.phtml
 */
/** @var $this Mage_Customer_Block_Form_Register */
?>
<?php
 
          $cooki = Mage::getModel('core/cookie');
 
          $cookie_user_name = $cooki->get('user_name');
 
          $cookie_user_password = $cooki->get('pass_user_name');
 
          $rememberme = $cooki->get('rememberme');
 
?>
<div class="well-block" style="margin-top:30px;">

    <div class="page-title">
        <h1 id="login_register"><?php echo $this->__('Login or Register') ?></h1>  
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 validation-advice">
         <?php
            $session = Mage::getSingleton("core/session",  array("name"=>"frontend"));
            echo $session->getData("loginmsg");
            $sessionmsg = Mage::getSingleton("core/session",  array("name"=>"frontend"));
            $sessionmsg->setData("loginmsg",'');
            ?>
			
			<input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />

			
            <?php echo $this->getChildHtml('form_fields_before')?>
			
         	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
				  
				  
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            
            <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
                <div class="register">
                    

                    <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center"><?php echo $this->__('New Customer') ?></h3>
                    <p><?php echo $this->__('By creating an account you will be able to track your orders. Store multiple addresses and much more.') ?></p>

                    <ul class="form_fields">
                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                               
                        <li>
                           <div class="input-box">
                           <input maxlength="10" type="text" placeholder="* Mobile Number" name="mobile" id="mobile" value="<?php echo $this->htmlEscape($this->getFormData()->getMobile()) ?>" title="<?php echo $this->__('Mobile No.') ?>" class=" input-text required-entry" />
                           </div>
                        </li>
                        
                        <li>
                            <div class="input-box">
                            <input type="text" placeholder="Email Address" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text  validate-emai" />
                            </div>
                        </li> 
                        
                        <?php if ($this->isNewsletterEnabled()): ?>
                 

                        <?php endif ?>
                    <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                    <?php if ($_dob->isEnabled()): ?>
                        <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
                    <?php endif ?>
                    <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                    <?php if ($_taxvat->isEnabled()): ?>
                        <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
                    <?php endif ?>
                    <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                    <?php if ($_gender->isEnabled()): ?>
                        <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
                    <?php endif ?>
                    </ul>





            <?php if($this->getShowAddressFields()): ?>
                    <input type="hidden" name="create_address" value="1" />
                    <h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
                    <ul >
                        <li>
                            <input type="text" placeholder="Company" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                        </li>
                        <li class="right">
                            <input type="text" placeholder="* telephone" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                        </li>
                    <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                        <li>
                                <input type="text" placeholder="* Street Address" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                        </li>
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <li class="right">
                                <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                        </li>
                    <?php endfor; ?>
                        <li>
                            <input type="text" placeholder="* City" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                        </li>
                        <li>
                            <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                                    //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                                    //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </li>
                        <li>
                            <input type="text" placeholder="* Zip/Postal Code" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                        </li>
                        <li>
                            <?php echo $this->getCountryHtmlSelect() ?>>
                        </li>
                    </ul>
                    <input type="hidden" name="default_billing" value="1" />
                    <input type="hidden" name="default_shipping" value="1" />

            <?php endif; ?>


                
                
				
                    <ul class="col-lg-12 col-md-12 col-sm-12 col-xs-12 password_fields">

                        <li>
                            <div class="input-box">
                            <input type="password" placeholder="* Password" name="password" id="password" title="<?php echo $this->__('* Password') ?>" value="" class="input-text required-entry validate-password" />
                            </div>
                        </li>
                        <li>
                            <div class="input-box">
                            <input type="password" placeholder="* Confirm Password" name="confirmation" title="<?php echo $this->__('* Confirm Password') ?>" id="confirmation" value="" class="input-text required-entry validate-cpassword" />
                            </div>
                        </li>
                        
                        
                        
                        <!-- New Requirement Start -->
                        <li>
                        <div class="input-box">        
                        <?php 
                          $attributePrimary = Mage::getModel('eav/config')->getAttribute('customer', 'primary_select');
                          $allOptionsPrimary = $attributePrimary->getSource()->getAllOptions(true, true); 
                        ?>
                        <select id="primary_select" name="primary_select" value="<?php echo $this->escapeHtml($this->getFormData()->getPrimarySelect()) ?>" class="validate-select">
                            <option value="">Primarily, I am a .. (Select One)</option>
                            <?php foreach ($allOptionsPrimary as $instancePrimary): ?>
                            <?php if($instancePrimary['value']){ ?>
                            <option value="<?php echo $instancePrimary['value']; ?>"><?php echo $instancePrimary['label']; ?></option>
                            <?php } ?>
                            <?php endforeach; ?>
                            </select>
                        </div>
                        </li>
						
                        <li class="secondary_select_hole">
                        <div class="input-box">
                        <?php 
                          $attributeSecondary = Mage::getModel('eav/config')->getAttribute('customer', 'secondary_select');
                          $allOptionsSecondary = $attributeSecondary->getSource()->getAllOptions(true, true); 
                          $lastItem = end($allOptionsSecondary);
                        ?>
						 <dl class="dropdown-selection"> 
							<dt>
							<a>                                   
							  <p class="multiSel"><span class="hida">I am also .. (Select Multiple)</span> </p>  
							</a>
							</dt>  
							<dd>
								<div class="mutliSelect">
									<ul>
									    <?php foreach ($allOptionsSecondary as $instanceSecondary): ?>
                                        <?php if($instanceSecondary['value']){ ?>
										<li><label><input type="checkbox" id="<?php echo $instanceSecondary['label']; ?>" name="secondary[]" data-val="<?php echo $instanceSecondary['label']; ?>" value="<?php echo $instanceSecondary['value']; ?>" /><?php echo $instanceSecondary['label']; ?></label></li>
										<?php } ?>
                                        <?php endforeach; ?>
									</ul>
								</div>
							</dd>
						</dl> 
						<input type="hidden" name="secondary_select" id="secondary_select" value="<?php echo $this->escapeHtml($this->getFormData()->getSecondarySelect()) ?>" />
                        </div>   
                        </li>
						
                        <li>                        
                        <div class="input-box" id="builderSelect" style="display:none;">
                            <input type="text" placeholder="Name of builder Company" name="builder_company" id="builder_company" value="<?php echo $this->escapeHtml($this->getFormData()->getBuilderCompany()) ?>" class="input-text" />
                        </div>
                        </li>
						
						<li>                        
                        <div class="input-box" id="otherSelect" style="display:none;">
                            <input type="text" placeholder="Others" name="others_customer" id="others_customer" value="<?php echo $this->escapeHtml($this->getFormData()->getOthersCustomer()) ?>" class="input-text" />
                        </div>
                        </li>
                        
                        <script>
						
						 if(jQuery('#Customer').is(":checked")){
							  
							  var html = '<span title="Customer">Customer,</span>';
							  jQuery('.multiSel').append(html);
							  jQuery(".hida").hide();
							  jQuery('#secondary_select').val(jQuery('#Customer').val());
						  } 
		
                        //Primary Select Start
                        jQuery('#primary_select').on('change', function() {
                        var selectedPrimary = jQuery('#primary_select option:selected').text();
                        if(selectedPrimary == 'Builder')
                        {
                        jQuery('#builderSelect').css('display','block');
                        jQuery('#builder_company').addClass('required-entry');                      
                        }
                        else
                        {
                        jQuery('#builderSelect').css('display','none'); 
                        jQuery('#builder_company').removeClass('required-entry');
                        }
						
						if(selectedPrimary == 'Others')
                        {
						jQuery('.secondary_select_hole').css('display','none');	
                        jQuery('#otherSelect').css('display','block');
                        jQuery('#others_customer').addClass('required-entry');
						jQuery('#Builder').prop('checked', false);
                        jQuery('#builderSelect').css('display','none'); 
                        jQuery('#builder_company').removeClass('required-entry');
						jQuery('#builder_company').val('');
                        jQuery('#secondary_select').val('');
                        }
                        else
                        {
						jQuery('.secondary_select_hole').css('display','block');	
                        jQuery('#otherSelect').css('display','none'); 
                        jQuery('#others_customer').removeClass('required-entry');
						jQuery('#others_customer').val(''); 				
                        }
						
						

                        //Call Secondary
                        if(jQuery('#Builder').is(":checked"))
						{
						jQuery('#builderSelect').css('display','block'); 
						}
                        
                        })
                        //Primary Select End
                        
                        //Secondary Select Start
                        jQuery(".mutliSelect ul").click(function(){
                        var output = jQuery.map(jQuery(':checkbox[name=secondary\\[\\]]:checked'), function (n, i) {
						return n.value;
						}).join(',');
						jQuery('#secondary_select').val(output);
                        
						if(jQuery('#Builder').is(":checked"))
						{
						jQuery('#builderSelect').css('display','block'); 
						jQuery('#builder_company').addClass('required-entry');
						}
						else
						{
						jQuery('#builderSelect').css('display','none'); 
						jQuery('#builder_company').removeClass('required-entry');
						}
						
						if(jQuery('#Others').is(":checked"))
						{
						jQuery('#otherSelect').css('display','block'); 
						jQuery('#others_customer').addClass('required-entry');
						}
						else
						{
						jQuery('#otherSelect').css('display','none'); 
						jQuery('#others_customer').removeClass('required-entry');
						}
						
						
                        //Call Primary
                        var selectedPrimary = jQuery('#primary_select option:selected').text();
                        if(selectedPrimary == 'Builder')
                        {
                        jQuery('#builderSelect').css('display','block');    
                        }
						
						
						
						
						
						
                        });
                        //Secondary Select End
                        </script>
               
                    <!-- New Requirement End -->
                        
                         
                        
                        <?php echo $this->getChildHtml('form.additional.info'); ?>
                        <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        <div class="clearfix"></div>
                        <li style="padding-bottom: 20px;">
                            <input type="checkbox" name="terms" id="terms" class="required-entry    exclusive_checkli   checkbox_display" style="margin-top: 3px; margin-bottom:18px;"><label style="color:#444;padding-right:5px;">I agree to</label><a class="terms-conditions" href="<?php echo $this->getUrl('terms_and_conditions'); ?>" target="__blank">Terms & Conditions</a>
							<input type="hidden" name="termandcondition_accept" id="termandcondition_accept" value="Yes" />
                        </li>
                        <li class="col-lg-12 col-md-12 col-sm-12 col-xs-12  exclusive_checkli"> <input type="checkbox"  class="exclusive_check"><label>I'd Like to receive exclusive offers and news.</label></li>
                       
                        <li class="right col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center creat_account" style="margin-top:30px;">
                            <button type="submit" title="<?php echo $this->__('REGISTER') ?>" class="button form-validate"><span><?php echo $this->__('REGISTER') ?></span></button>
                        </li>
                    </ul>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>  

                </div> 

                </form>



                <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                    <input name="context" type="hidden" value="checkout" />
                <?php endif; ?>
            
    </div>

    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <form action="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) ?>customer/account/loginPost/" method="post" id="login-form1">
                   
                <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                
                    <div class="login_panel">
                        <h3 class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><?php echo $this->__('Existing  Customer') ?></h3>
                        <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                        <ul>
                            <li class"col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <input type="text" name="login[username]" maxlength="10" placeholder="* Mobile Number" value="<?php if($cookie_user_name != " "){ echo $cookie_user_name;}else{ echo $this->htmlEscape($this->getUsername()); } ?>" id="email" class="input-text required-entry mobile2" title="<?php echo $this->__('Mobile Number') ?>" />
                            </li>
                            <li class"col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <input type="password" class="col-lg-12 col-md-12 col-sm-12 col-xs-12 custominput required-entry validate-password" name="login[password]" placeholder="* Password" value="<?php if($cookie_user_password != ''){ echo $cookie_user_password;}?>" id="pass" title="<?php echo $this->__('Password') ?>"/>
                                <input type="checkbox" name="rememberme" id="login_checkbox"><label id="remember_login">Remember me</label>
                                
                                
                            </li>
                            <li class="right col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center creat_account" style="margin-top:20px;">
                                <button type="submit" class="submit login-form1" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><!--<span><img src="<?php echo $this->getSkinUrl('images/submit_arrow.jpg'); ?>" /></span> --> LOGIN </button>                     
                            </li>
                            
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                        </ul>
                        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>

                       
                        <span class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center required-field-login"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>customer/account/forgotpassword/" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a></span>

                     <!-- <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <span class="or"><img src="<?php echo $this->getSkinUrl('images/or.jpg'); ?>" /></span>
                        </div>
                        <span class="col-lg-6 col-md-6 col-sm-12 col-xs-12"><a href="https://www.facebook.com/mSupplydotcom?fref=ts" target="_blank"><img src="<?php  echo $this->getChildHtml('inchoo_socialconnect_facebook_login_button'); ?>" /></a></span>
                        <span class="col-lg-6 col-md-6 col-sm-12 col-xs-12">   </span> -->
                    </div>
                </form>
    </div>
</div>


    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>

        <script type="text/javascript">
    //<![CDATA[
        var dataForm1 = new VarienForm('login-form1', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
<style>.error3{color:#ec5523;}.error4{color:#ec5523;}.error1{color:#ec5523;}.error2{color:#ec5523;}.errormobi1{color:#cc3300;}</style>  
<script type="text/javascript">
    
jQuery(document).ready(function() {

    jQuery('.form-validate').click(function() {
        dataForm.validator.validate();
        /** ===== First Name ===== **/
        jQuery(".error1").hide();
        var hasError = 0;
        var nameregex =/^[a-zA-Z. ]+$/;
        var nameaddressVal = jQuery("#firstname").val();
        if(nameaddressVal != "")    {
            jQuery("#advice-required-entry-firstname").css({
                        "opacity": "0",
                        "display": "none"
                        });         
        }
        if(nameaddressVal == "")    {
            jQuery("#advice-required-entry-firstname").css({
                        "opacity": "999",
                        "display": "block"
                        });         
        }
        else if(!nameregex.test(nameaddressVal)) {
            jQuery("#firstname").after('<span class="error1">Enter Valid First Name.</span>');
            jQuery("#advice-required-entry-firstname").css({
                        "opacity": "0",
                        "display": "none"
                        });
            hasError = 1;
        }
        /** ===== First Name ====== **/
        
        /** ===== Last Name ======= **/
        jQuery(".error2").hide();
        
        var lnameregex =/^[a-zA-Z. ]+$/;
        var lnameaddressVal = jQuery("#lastname").val();
        if(lnameaddressVal != "")   {
            jQuery("#advice-required-entry-lastname").css({
                        "opacity": "0",
                        "display": "none"
                        });         
        }
        if(lnameaddressVal == "")   {
            jQuery("#advice-required-entry-lastname").css({
                        "opacity": "999",
                        "display": "block"
                        });
                
        }
        else if(!lnameregex.test(lnameaddressVal)) {
            jQuery("#lastname").after('<span class="error2">Enter Valid Last Name.</span>');
            jQuery("#advice-required-entry-lastname").css({
                        "opacity": "0",
                        "display": "none"
                        });
            hasError = 1;
        }
        /** ===== Last Name ===== **/
        
        /** ===== Email Address ===== **/
        jQuery(".error3").hide();
    
        var emailblockReg = /^([0-9a-zA-Z\-_.]+@[a-zA-z]{2,7}([\w-]+\.)+[\w-]{2,4})?$/;
        var emailaddressVal = jQuery("#email_address").val();
    
        if(!emailblockReg.test(emailaddressVal)) {
            jQuery("#email_address").after('<span class="error3">Enter Valid Email Address.</span>');
            
            hasError = 1;
        }
        /** ===== Email Address ===== **/
        
        /** ===== Mobile Number ===== **/
        jQuery(".error4").hide();
        
        var mobiReg = /^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[789]\d{9}$/;
        var mobileVal = jQuery("#mobile").val();
        
        if(mobileVal == '') {
                jQuery("#advice-required-entry-mobile").css({
                        "opacity": "999",
                        "display": "block"
                        });
        }
        else if(!mobiReg.test(mobileVal)) {
            jQuery("#mobile").after('<span class="error4">Enter Valid Mobile Number.</span>');
            jQuery("#advice-required-entry-mobile").css({
                        "opacity": "0",
                        "display": "none"
                        });
            hasError = 1;
        }       
        else
        {
            jQuery("#advice-required-entry-mobile").css({
                        "opacity": "0",
                        "display": "none"
                        });
        }
        
        /** ===== Mobile Number ===== **/
        
        /** ===== Password ===== **/
            
        var password = jQuery("#password").val();
        var lent = jQuery("#password").val().length;
        
        if(lent < 6 && password != ''){
        jQuery("#advice-required-entry-password").css({
                            "opacity": "0",
                            "display": "none"
                            });
        hasError = 1;
        }else{
        jQuery("#password").after('<span class="error1"></span>');
        jQuery("#advice-required-entry-password").css({
                            "opacity": "999",
                            "display": "block"
                            });
        jQuery("#advice-required-entry-password").css({
                    "opacity": "0",
                    "display": "none"
                    });
                    
        }
        
       if(password != '') {
        jQuery("#advice-required-entry-password").css({
                    "opacity": "0",
                    "display": "none"
                    });
                    
        }else{
            
            jQuery("#advice-required-entry-password").css({
                            "opacity": "999",
                            "display": "block"
                            });
                            
        }
        /** ===== Password ===== **/
        
        /** ===== Confirm Password ===== **/
            
        var cpassword = jQuery("#confirmation").val();
        var clent = jQuery("#confirmation").val().length;

        if(clent < 6 && cpassword != ''){
        jQuery("#advice-validate-password-pass").css({
                            "opacity": "0",
                            "display": "none"
                            });
        hasError = 1;
        
        }else{
        jQuery("#confirmation").after('<span class="error1"></span>');
        jQuery("#advice-validate-password-pass").css({
                            "opacity": "999",
                            "display": "block"
                            });
        }
        
       if(cpassword != '') {
        jQuery("#advice-validate-cpassword-confirmation").css({
                    "opacity": "0",
                    "display": "none"
                    });
        jQuery("#advice-required-entry-confirmation").css({
        "opacity": "0",
        "display": "none"
        });
        
                    
        }else{
        
        jQuery("#advice-validate-cpassword-confirmation").css({
                        "opacity": "999",
                        "display": "block"
                        });
        jQuery("#advice-required-entry-confirmation").css({
                        "opacity": "999",
                        "display": "block"
                        });             
                        
                        
        }       
        /** ===== Confirm Password ===== **/
        
        if(hasError == 1)
         {
            return false;
         }else{
             return true;
         }      
         
         
        
   });
   
   
   /** Login Form **/
   
   jQuery('.login-form1').click(function() { 
    dataForm1.validator.validate();
    jQuery(".error1").hide();
    jQuery(".errormobi1").hide();
    var hasErrorpass = false;
    var hasErrormobi1 = false;
    var mobiRegm1 = /^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[789]\d{9}$/;
    
    var password = jQuery("#pass").val();
    var lent = jQuery("#pass").val().length;
    
    var mobilenVal = jQuery(".mobile2").val();

    if(lent < 6 && password != ''){
    
    jQuery("#advice-validate-password-pass").css({
                            "opacity": "0",
                            "display": "none"
                            });
    hasErrorpass = true;
    
    }else{
        jQuery("#pass").after('<span class="error1"></span>');
        jQuery("#advice-validate-password-pass").css({
                            "opacity": "999",
                            "display": "block"
                            });
    }
    
   if(password != '') {
        jQuery("#advice-required-entry-pass").css({
                    "opacity": "0",
                    "display": "none"
                    });
    }else{
        jQuery("#advice-required-entry-pass").css({
                        "opacity": "999",
                        "display": "block"
                        });
    }
     
    if(mobilenVal == '') {
        jQuery("#advice-required-entry-email").css({
                    "opacity": "999",
                    "display": "block"
                    });
    }

    else if(!mobiRegm1.test(mobilenVal)) {
        jQuery(".mobile2").after('<span class="errormobi1">Enter Valid Mobile Number.</span>');
        jQuery("#advice-required-entry-email").css({
                        "opacity": "0",
                        "display": "none"
                        });
        hasErrormobi1 = true;
    }else
    {
        jQuery("#advice-required-entry-mobile").css({
                    "opacity": "0",
                    "display": "none"
                    });
    }

      
     
    
    if(hasErrormobi1 == true) { 
        return false; 
    }
    else if(hasErrorpass == true) {
            return false;
        }       
  
   
    });
   
});
</script>
<style>
.error1{ clear:both; float:left;}
.multiSel span{background: #ccc none repeat scroll 0 0;border-radius: 5px;float: left;margin: 2px;padding: 5px;}
.hida {background: rgba(0, 0, 0, 0) none repeat scroll 0 0 !important;}	
</style>