 <div class="separate-blocks">
 <!--   <div class="tips-section"></div>-->
            <h3>Did you know...</h3>
            <div class="clearfix"></div>
       
            <div class="fadein"><p id="changeText"> When cement is exposed to moisture, it solidifies, store carefully!</p></div>
         </div>

<div class="know_more"> 
            <div class="clearfix"></div>
            <h2>Looking for Contractor, Architect, Carpenter, Interior Designer...</h2>
           <form action="<?php echo $this->getUrl('knowmore/index/knowmore') ?>" id="knowmoreForm" method="post">
              <input type="text" placeholder="Name" name="name" id="name" class="required-entry" />              
              <input type="text" placeholder="Phone" name="phone" id="phone" class="required-entry validate-digits validate-length maximum-length-10 minimum-length-10" />
              <input type="text" placeholder="Email" name="email" id="email" class="required-entry validate-email" />
              <textarea title="Message" placeholder="Message" name="message" id="comment" class="required-entry"></textarea>
            <button type="submit" class="know_more_btn" style="width:100%">Ask Now</button>
           </form>
           <div id="formSuccess1" style="display:none;color:white;clear:both;"></div>
</div>  

<script type="text/javascript">
//<![CDATA[
    var knowmoreForm = new VarienForm('knowmoreForm', false);
//]]>

//<![CDATA[
    var formId1 = 'knowmoreForm';
    var myForm1 = new VarienForm(formId1, false);
    var postUrl1 = '<?php echo $this->getUrl('knowmore/index/knowmore') ?>';
	var postapi = '<?php echo $this->getUrl('knowmore/index/senddatatoadjetter') ?>';
	 function doapiAjax1() {
        jQuery('#formSuccess1').html('');
        if (myForm1.validator.validate()) {
            new Ajax.Updater(
                { success:'formSuccess' }, postapi, {
                    method:'post',
                    asynchronous:true,
                    evalScripts:false,
                    onComplete:function(request, json) {
                    },
                    onLoading:function(request, json){
                        Element.show('formLoader');
                    },
                    parameters: $(formId1).serialize(true),
                }
            );
        }
    }
    function doAjax1() {
        jQuery('#formSuccess1').html('');
        if (myForm1.validator.validate()) {
            new Ajax.Updater(
                { success:'formSuccess' }, postUrl1, {
                    method:'post',
                    asynchronous:true,
                    evalScripts:false,
                    onComplete:function(request, json) {
                        //Element.hide(formId);
                        document.getElementById(formId1).reset();
                        jQuery('#formSuccess1').html('');
                        Element.show('formSuccess1');
                        var div = document.getElementById('formSuccess1');
                        div.innerHTML = div.innerHTML + 'Thank You. Our expert will contact you.';
                        
                    },
                    onLoading:function(request, json){
                        Element.show('formLoader');
                    },
                    parameters: $(formId1).serialize(true),
                }
            );
        }
    }
    
    new Event.observe(formId1, 'submit', function(e){
        e.stop();
		doapiAjax1();
        doAjax1();
    });
//]]>
</script>