<?php
    $APIURL = Mage::getStoreConfig('configuration/configuration_homepage/homepageproductsapiurl')."p7";
    $ch = curl_init($APIURL);
	curl_setopt($ch, CURLOPT_URL,$APIURL);
	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $NewProducts=json_decode(curl_exec($ch));
	curl_close($ch);
    $liClasses = array ("col-xs-12 divider",
                        "col-xs-12 divider",
                        "col-xs-12 divider",
                        "col-xs-12 divider",
                        "col-xs-12 divider",                        
                        "col-xs-12 divider",
                        "col-xs-12 divider",
                        "col-xs-12 divider",
                        "col-xs-12 divider",
                        "col-xs-12 divider",
                        "col-xs-12 divider",
                        "col-xs-12 divider",
                        "col-xs-12 divider",
                        "col-xs-12 divider",
                        "col-xs-12 divider");
?> 
<div id="produts_nav">
			<h1 class="fade-line"><?=$NewProducts->title;?></h1>
          <div class="carousel slide">
                 <ul class="best_products_section" id="kitchenSlide">
                    <?php
                        for($i=0;$i<15;$i++)
                        {
                     ?>
                            <li class="<?php echo $liClasses[$i]; ?> item">   
								<a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$NewProducts->products[$i]->request_path; ?>">
									<img src="<?php echo $NewProducts->products[$i]->ImageURL; ?>" alt="msupply" width="170" height="235"/>
								</a>	
								<div class="hmptitleblock"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).$NewProducts->products[$i]->request_path; ?>" class="hmptitle" title="<?php echo $NewProducts->products[$i]->Product_Name;  ?>"> <?php echo $NewProducts->products[$i]->Product_Name; ?></a></div>
                            	    <div class="price_tag wishlist_price">                                         
								<?php if($NewProducts->products[$i]->Special_Price !=''){ ?>	
								<span class="old-price">
									<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Price,'0'); ?>
								</span> 
							<span class="discount">
							<?php if($NewProducts->products[$i]->Special_Price) {?>
								<?php
									$price_prod = $NewProducts->products[$i]->Price; 
								    $spl_price_prod = $NewProducts->products[$i]->Special_Price;
                                    $discount = (($price_prod - $spl_price_prod)/$price_prod)*100;
								?>
								(<?php echo number_format($discount,0);?>% Off)
								<?php } ?>
							</span><br><br>
								<?php
									$date = date("Y-m-d");
									if($NewProducts->products[$i]->Special_Price_From_Date !='' && $NewProducts->products[$i]->Special_Price_From_Date >= $date )
									{
										$date1=date_create($NewProducts->products[$i]->Special_Price_From_Date);
										$date2=date_create($NewProducts->products[$i]->Special_Price_To_Date);
										$diff=date_diff($date1,$date2);
										$sign = $diff->format("%R");
										$days = $diff->format("%a");
										if($sign == '+' && $days >= 0)
										{ ?>
											<span class="special-price"> <?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Special_Price,'0'); ?> </span>
								 <?php 	}
									} else if($NewProducts->products[$i]->Special_Price_From_Date =='' && $NewProducts->products[$i]->Special_Price_To_Date =='' ){
								 ?>									
									<span class="special-price"> <?php  echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Special_Price,'0'); ?></span>
								<?php }
								}else { ?>
									<span class="regular-price">
										<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol() . number_format($price = $NewProducts->products[$i]->Price,'0'); ?>
									</span>
								<?php }	?>
								<?php 
									  if($NewProducts->products[$i]->Product_Unit != "")
									   echo " / ".$NewProducts->products[$i]->Product_Unit;
								?>
                            </div>							
                          </li>
                    <?php                                
                        }
                    ?>
                  </ul>      
        </div>
</div>
