<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/prod_upload.css'); ?>" type="text/css" />
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="header">
	<div class="contenar">
		<div class="logo"><img src="<?php echo $this->getSkinUrl('images/mSupply-logo-revised.png') ?>"></div>
	</div>
</div>
<div class="contenar">
	<div class="banner">
		<h2>Welcome To <br>Product Upload</h2>
	</div>
	<div class="ban_shadow"><img src="<?php echo $this->getSkinUrl('images/banner_shadow.png') ?>"></div>
	<div class="clearfix"></div>
		
	
	<div class="content">

	<form id="doc-form" name="doc-form" method="post" action="<?php echo Mage::getUrl(); ?>productupload/index/produpload" enctype="multipart/form-data">
		<h3>Upload Document</h3>
		<input class="docname required-entry" type="file" title="File" name="docname">
		<button class="btn" type="submit" title="Save"><span>Upload</span></button>                    
	</form>


	</div>
	
</div>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('doc-form', true);
    //]]>
    </script>