<div>
<span style="line-height: 30px;height:30px;width: 100%; float: left;text-align:center;font-size:10px;">
		<span style="color:#FDC005"><img src="<?php echo $this->getSkinUrl('images/whatsapp.png'); ?>"></span>
		WhatsApp to Order Now! <b>7899777078</b> - Bangalore <b>/</b> <b>7899901142</b> - Mysore
	</span>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 hero-slider-block">
<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('home-page-menu')->toHtml();?>
<!-- Carousel-->
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('new-home-slideshow')->toHtml();?>
<!-- /.carousel -->
</div>
</div>
 