<?php
/*------------------------------------------------------------------------
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

global $var_yttheme;  
// Include cpanel
if( $var_yttheme->getParam('showCpanel') ) { ?>
<div id="cpanel_wrapper">
	<!--<div class="cpanel-head">
		<span>Theme setting</span>
		<div class="action cpanel-reset">
			<a class="btn btn-info reset" href="#" onclick="javascript: onCPResetDefault(TMPL_COOKIE);">Reset</a>
		</div>		
	</div>-->

	<div class="accordion" id="ytcpanel_accordion">

		<div class="feedback-form">

			<p class="feed-firstline">Tell us what you think.</p>
			<p class="feedmsg">Love us / have suggestions / ideas / feature requests? Tell us how we can improve our website.</p>
			
			<form action="<?php echo $this->getUrl('feedback/index/save'); ?>" id="feedForm" name="feedForm" type="post" >
			
				<div class="pinresult-container" style="display:none;"></div>
							
                <div class="feedback-field">
                        <input type="text" class="input-text cpadin required-entry whitebg  type="text"font11 required-entry validate-name" placeholder=" Name "/ name="name" id="name"> 
						
                </div>
								
                <div class="feedback-field">
                        <input type="text" class="input-text cpadin required-entry whitebg font11 required-entry validate-email" placeholder=" * Email "/ name="email" id="email"> 
						<div class="fb-err-email"></div>
                </div>
								
                <div class="feedback-field">
                        <input type="text" class="input-text cpadin required-entry whitebg font11 required-entry validate-length maximum-length-10 minimum-length-10 validate-digits" placeholder=" * Phone "/ name="phone" id="phone">
						<div class="fb-err-phone"></div>
                </div>
				                
                <div class="feedback-field">
                        <select class="input-text cpadin required-entry font11 whitebg validate-select" name="help" id="help">
						<option value="">* Please select the Category</option>
						<option value="Unable to find a product">Unable to find a product</option>
						<option value="Not getting a good price">Not getting a good price</option>
						<option value="Customer Service">Customer Service</option>
						<option value="Delivery Issues">Delivery Issues</option>
						<option value="Other Suggestions">Other Suggestions</option>
						</select>
						<div class="fb-err-help"></div>
                </div>
                
                <div class="feedback-field">
                        <textarea class="input-text required-entry ctxtar font11 whitebg required-entry" placeholder=" * Message"  cols="10" rows="5" name="comment" id="comment"></textarea> 
						<div class="fb-err-comment"></div>
                        
                </div>
               

               <div class="feedback-field"> <input type="button" value="Submit" id="feedback-button" class="button feed-button" name="feedback-button" ></div>
			   <div id="interaction_div"></div>
			   
			   
             </form>

		</div><!-- feedback form end-->


		<!--Theme
        <div class="accordion-group cpanel-theme-color">
            <div id="yt_cpanelaccordionfirst" class="accordion-heading">
                <a class="accordion-toggle"  data-parent="#ytcpanel_accordion" href="#ytitem_1">
					Theme Color
				</a>
            </div>
        	<div id="ytitem_1" class="accordion-theme">
                <div class="accordion-inner clearfix">
					<div class="color-theme">
						<?php
							$storeCode = Mage::app()->getStore()->getCode();
							//var_dump($storeCode);
						?>
						<a class="theme-color yellow <?php if($storeCode == 'english') echo 'active';?>" href="<?php echo $this->getUrl('') ?>?___store=english&amp;___from_store=australia"><span title="Yellow" >Yellow</span></a>
						<a class="theme-color blue <?php if($storeCode == 'australia') echo 'active';?>" href="<?php echo $this->getUrl('') ?>?___store=australia&amp;___from_store=english"><span title="Blue" >Blue</span></a>
                        <a class="theme-color tangerine <?php if($storeCode == 'german') echo 'active';?>" href="<?php echo $this->getUrl('') ?>?___store=german&amp;___from_store=english"><span title="Tangerine" >Tangerine</span></a>
						<a class="theme-color emerald <?php if($storeCode == 'italia') echo 'active';?>" href="<?php echo $this->getUrl('') ?>?___store=italia&amp;___from_store=english"><span title="Emerald" >Emerald</span></a>
						<a class="theme-color green <?php if($storeCode == 'canada') echo 'active';?>" href="<?php echo $this->getUrl('') ?>?___store=canada&amp;___from_store=english"><span title="Green" >Green</span></a>
						
					</div>
				</div>
			</div>
        </div>-->
	
		<!--Store-->
		<!--<div class="accordion-group cpanel-store">
			<div class="accordion-heading">
				<a class="accordion-toggle" data-parent="#ytcpanel_accordion" href="#ytitem_2">
				Layout Style</a>
			</div>
			<div id="ytitem_2" class="accordion-store">
				<div class="accordion-inner clearfix">
					<div class="cp-item">
						<div class="inner">
							<?php //echo $this->getChildHtml('store_switcher');?>
						</div>
					</div>-->
					<!-- Select Layout -->
					<!--<div class="cp-item layout-option">
						<div class="inner">
							<select onchange="javascript: onCPApply();" name="ytcpanel_layoutstyle" class="cp_select">
								<option value="1" <?php //echo ($var_yttheme->getParam('layoutstyle')=='1')?' selected="selected"':'';?>>Full Width</option>
								<option value="2" <?php //echo ($var_yttheme->getParam('layoutstyle')=='2')?' selected="selected"':'';?>>Boxed</option>
							</select>
						</div>
					</div>					
				</div>
			</div>
		</div>-->
		<!-- Menu 
		<div class="accordion-group cpanel-menu">
			<div class="accordion-heading">
				<a class="accordion-toggle" data-parent="#ytcpanel_accordion" href="#ytitem_6">
				Menu style </a>
			</div>
			<div id="ytitem_6" class="accordion-menu">
				<div class="accordion-inner clearfix">
					
					<div class="cp-item footer-background-color">
					
						<div class="inner">
							<select onchange="javascript: onCPApply();" name="ytcpanel_menustyle" class="cp_select">
								<option value="mega" <?php echo ($var_yttheme->getParam('menustyle')=='mega')?' selected="selected"':'';?>>Mega</option>
								<option value="css" <?php echo ($var_yttheme->getParam('menustyle')=='css')?' selected="selected"':'';?>>Css</option>
							</select>
						</div>
					</div>
				</div>
			</div>
		</div>-->


	</div>
	<div id="cpanel_btn" class="normal">
		<span class="feedback"></span>
	</div>
</div>

<script type="text/javascript">
	jQuery(document).ready(function($){
		$('.theme-color').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
		});
	});
    </script>
<script type="text/javascript">
//<![CDATA[
    var feedForm = new VarienForm('feedForm', false);
//]]>
</script>	
	
	<script>
jQuery(document).ready(function(){
    jQuery('#feedback-button').click(function(){
	  var fbemail = jQuery("#email").val()		
	  var fbphone = jQuery("#phone").val()
	  var fbhelp = jQuery("#help").val()
	  var fbcomment = jQuery("#comment").val()
		
		if (fbemail=="")
		{
			jQuery('.fb-err-email').html('Please enter your email address.');
			jQuery('.fb-err-help').html('');
			jQuery('.fb-err-phone').html('');
			jQuery('.fb-err-comment').html('');
			 
		} 
		else if (fbphone=="")
		{
			jQuery('.fb-err-phone').html('Please enter your mobile number.');
			jQuery('.fb-err-email').html('');
			jQuery('.fb-err-help').html('');
			jQuery('.fb-err-comment').html('');
			
		}
		else if (fbhelp=="")
		{
			jQuery('.fb-err-help').html('Please select your category.');
			jQuery('.fb-err-email').html('');
			jQuery('.fb-err-phone').html('');
			jQuery('.fb-err-comment').html('');
			
		}
		else if (fbcomment=="")
		{
			jQuery('.fb-err-comment').html('Please enter your comment.');
			jQuery('.fb-err-email').html('');
			jQuery('.fb-err-phone').html('');
			jQuery('.fb-err-help').html('');
			
		}
		else
		{
			jQuery.ajax({
				
			  type: 'POST',
			  data:jQuery('#feedForm').serialize(),
			
			  url:'<?php echo Mage::getUrl(); ?>feedback/index/save',
				beforeSend:function(){
					jQuery("#interaction_div").html("<img src='<?php echo $this->getSkinUrl('images/loading.gif') ?>' /> ");
				},
			
			  success: function(response){
			  jQuery('.pinresult-container').show()
			  jQuery('.fberro').html()
			  jQuery('.pinresult-container').html('Thank you for your feedback.').hide().fadeIn(1000, function() {jQuery(".pinresult-container").append("");
                        }).delay(1000).fadeOut(1000);
									
			  jQuery("#interaction_div").html("");
			  jQuery('.fb-err-email').hide();
			  jQuery('input[type="text"],textarea,select').val('');
			}
			
			});
		
		}
	});
	
});
</script>


<?php } ?>
