<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer-top')->toHtml();?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer-bottom')->toHtml();?>

<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
	<div class="modal homepagefaq faqhow" role="dialog" style="z-index:99999;">
		<div class="modal-dialog appendcont">
		  
		</div>
	</div>
</div>
<script type="text/javascript">
	jQuery('.showfaqpopup').click(function(){
		var contid = jQuery(this).attr('id');
		jQuery('.appendcont').html('');
		jQuery('.appendcont').html(jQuery('.'+contid).html());
		jQuery('body').append('<div class="modal-backdrop fade in"></div>');
		jQuery('.appendcont').show();
		jQuery('.faqhow').show();
		
	});
	jQuery(document).on('click',".appendcont .close",function () {
		jQuery(".faqhow").hide();
		jQuery('.modal-backdrop').remove();
	});
</script>