
<ul class="nav nav-tabs cpaymenttab" role="tablist">
   <li role="presentation" class="active"><a href="#Address" aria-controls="home" role="tab" data-toggle="tab">Billing Address</a></li>
   <li role="presentation"><a href="#Address" aria-controls="home" role="tab" data-toggle="tab">Shipping Address</a></li>
   <li role="presentation"><a href="#Payment" aria-controls="messages" role="tab" data-toggle="tab">Payment</a></li>
   <li role="presentation"><a href="#Complete" aria-controls="settings" role="tab" data-toggle="tab">Complete</a></li>
</ul>
<form id="co-billing-form" action="">
   <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mt20 pad10">
      <div class="ship-address form-list" id="billing_fields">
         <h2>Billing Information</h2>

         <?php if ($this->customerHasAddresses()): ?>
         <div class="field">
            <div class="input-box">
              <div style="display:none;"> <?php echo $this->getAddressesHtmlSelect('billing') ?></div>
               
               <?php $customerId = Mage::getSingleton('customer/session')->getCustomer();?>    
				<?php $customer = Mage::getModel('customer/customer')->load($customerId->getId()); ?>
				<?php $data = array();?>

				<?php $address = $customer->getAddresses(); ?>
				<?php $i = 0; ?>
				<?php $no = count($address); ?>
				
				<?php foreach ($address as $addr):?>
				<?php $data = $addr->toArray();?>
				<?php if($i >= ($no-6)) { ?>
				<div id="addresseList<?php echo $data['entity_id'];?>" class="default-address-billing">
					<div id="<?php echo $data['entity_id'];?>" data-box="billing-address-select" data-count="<?php echo $no ?>" data-billing-zipcode="<?php echo $data['postcode'] ;?>" class="addressbox">
						<address class="bill-ship-block">                         
							<?php echo '<p class="last-first-name"><b>'.$data['firstname'].' '.$data['lastname'].'</b></p>';?>
							
							<a class="group1" title="<?php echo  $this->__('Edit') ?>" href="<?php echo Mage::getBaseUrl() . 'customer/address/edit/id/' . $data['entity_id']; ?>?popupEdit=1&meth=billing" ><i class="fa fa-pencil"></i></a>
							<a href="#" title="<?php echo  $this->__('Delete') ?>" class="link-remove" onclick="return deleteAddress('<?php echo $data['entity_id'];?>');"><i class="fa fa-trash-o"></i></a>
							
							<?php echo '<p>'.$data['street'].'</p>';?>
							<?php echo '<p>'.$data['city'].','.$data['region'].','.$data['postcode'].'</p>';?>
							<?php $country_name = Mage::app()->getLocale()->getCountryTranslation($data['country_id']);?>
							<?php echo '<p>'.$country_name.'</p>';?>
							<?php echo '<p>T: '.$data['telephone'].'</p>' ;?>
						</address>
					</div>
				
				</div>
				
				<?php } $i++;?>
				<?php endforeach;?>


        
            </div>
         </div>
         <?php endif; ?>
         
 

         <ul>
            <li id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
               <fieldset class="billing_form">
                  <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />       
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                     </div>
                  </div>
                 
				  
				  
                  <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <input  placeholder="*<?php echo $this->__('Address Line 1') ?>"  type="text" title="<?php echo $this->__('Address Line 1') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text street1 <?php echo $_streetValidationClass ?>" />
                     </div>
                  </div>
                  <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                  <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <input type="text"  placeholder="<?php echo $this->__('Address Line %s', $_i) ?>" title="<?php echo $this->__('Address Line %s', $_i) ?>" name="billing[street][]" id="billing:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text street2 <?php echo $_streetValidationClass ?>" />
                     </div>
                  </div>
                  <?php endfor; ?>
				   <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <input type="text"  maxlength="10" placeholder="*<?php echo $this->__('Telephone') ?>" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text mobile required-entry maximum-length-10 minimum-length-10 validate-digits validate-length <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" />
                     </div>
                  </div>
                  <?php if(!$this->isCustomerLoggedIn()): ?>
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <input placeholder="<?php echo $this->__('Email Address') ?>" type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                     </div>
                  </div>
                  <?php endif; ?>
                  <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <input type="text"  placeholder="<?php echo $this->__('VAT Number') ?>" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                     </div>
                  </div>
                  <?php endif; ?>
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <input type="text"  placeholder="*<?php echo $this->__('City') ?>" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?> city" id="billing:city" />
                     </div>
                  </div>
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <select  placeholder="*<?php echo $this->__('State/Province') ?>" id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select state" style="display:none;">
                           <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                           //<![CDATA[
                           	$('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                           //]]>
                        </script>
                        <input type="text"  placeholder="*<?php echo $this->__('State/Province') ?>" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?> state" style="display:none;" />
                     </div>
                  </div>
                  <!--<div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                     <input type="text"  placeholder="<?php echo $this->__('Fax') ?>" name="billing[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" id="billing:fax" />
                     </div></div>-->
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <input type="text" id="zip" placeholder="*<?php echo $this->__('Zip/Postal Code') ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" maxlength="6" class="zipbilling input-text required-entry  <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                     </div>
                  </div>
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12" style="float:right">
                     <div class="input-box">
                        <?php echo $this->getCountryHtmlSelect('billing') ?>
                     </div>
                  </div>
                 

                  <?php if(!$this->isCustomerLoggedIn()): ?>
                  <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                  <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                  <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
                  <?php if ($_dob->isEnabled()): ?>
                  <div class="field">
                     <div class="input-box">
                        <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                     </div>
                  </div>
                  <?php endif; ?>
                  <?php if ($_gender->isEnabled()): ?>
                  <div class="field">
                     <div class="input-box">
                        <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                     </div>
                  </div>
                  <?php endif ?>
                  <?php endif ?>
                  <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                  <?php if ($_taxvat->isEnabled()): ?>
                  <div class="field">
                     <div class="input-box">
                        <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                     </div>
                  </div>
                  <?php endif ?>
                  <div class="field">
                     <div class="input-box">
                        <input type="password"  placeholder="Password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                     </div>
                  </div>
                  <div class="field">
                     <div class="input-box">
                        <input type="password"  placeholder="Confirm Password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                     </div>
                  </div>
                  <?php endif; ?>
                  <!--<div class="field"  id="billing-buttons-container">
                     <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                      </div>-->
                  <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                  <div class="bilng-save">
                     <div class="save-address">
                        <input type="checkbox" checked="checked" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                     </div>
                  </div>
                  <?php else:?>
                  <input type="hidden" name="billing[save_in_address_book]" value="1" />
                  <?php endif; ?>
                  <?php echo $this->getChildHtml('form.additional.info'); ?>
                  <?php echo $this->getChildHtml('checkout.onepage.billing.extra')?>
               </fieldset>
            </li>
         </ul>
          
	   
		
			<div class="full-ship full-ship-bottom">
				<?php if ($this->canShip()): ?>
				<div class="biling-ship-address field col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
					<div class="ship-left">
						<input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" title="<?php echo  $this->__('Ship to this address') ?>" onclick="$('shipping:same_as_billing').checked = true;" class="radio sameshipaddr" />
						<label for="billing:use_for_shipping_yes"><?php echo  $this->__('Use this address to ship') ?></label>
					</div>
				</div>

				<?php endif; ?>
			</div>
			
			<?php if (!$this->canShip()): ?>
			<input type="hidden" name="billing[use_for_shipping]" value="1" />
			<?php endif; ?>
			
         <div class="field text-center"  id="billing-buttons-container">
            <div class="#input-box">
			
				<div class="addlimit" style="color: #bf4a32;font-size: 13px;text-align: center;"></div>
				<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12 text-center">
				<?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
				
				<span class="addnew">
					<button type="button" class="addnewaddress" data-box="billing-address-select" id="billing_add" value="<?php echo $this->__('Add New Address');?>">Add New Address</button>
				</span>
				
				<span class="cancel-btn" style="display:none;">
					<button type="button" class="addnewaddress cancel" data-box="billing-address-select" id="billing_cancel" value="<?php echo $this->__('Cancel');?>">Cancel</button>
				</span>
				
				<?php endif; ?>
				
               <button type="button" title="<?php echo $this->__('Save and Continue') ?>" class="savebtn check_billing"><span><span><?php echo $this->__('SAVE AND CONTINUE') ?></span></span></button>
			   
			   
               <span class="please-wait" id="billing-please-wait" style="display:none;">
               <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
               </span>
				</div>
         </div>
      </div>
   </div>
</form>
<script type="text/javascript">
   //<![CDATA[
       var billing = new Billing('co-billing-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveBilling') ?>');
       var billingForm = new VarienForm('co-billing-form');
   
       billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
       $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);
   		jQuery('#billing\\:country_id option[value=""]').hide();
       var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
   	
   //]]>
</script>
<script type="text/javascript">
	var selbill = jQuery('#billing-address-select').val();
	jQuery("#co-billing-form #"+selbill).addClass("selected");
	selectedBillingPincode = jQuery("#co-billing-form #"+selbill).attr('data-billing-zipcode');
	//jQuery(".input-box div:nth-child(2) .addressbox").addClass("selected")
	
	jQuery(".zipbilling").blur(function(){
    selectedBillingPincode = jQuery(this).val();
    });
	
   jQuery(".check_billing").click(function(){
  
   	if(jQuery('.sameshipaddr').is(':checked'))
   	{	
		
		 var cartcount = '<?php echo Mage::helper('checkout/cart')->getItemsCount(); ?>';
		 <?php 
			$quote = Mage::getSingleton('checkout/session')->getQuote();
			$cartItems = $quote->getAllVisibleItems();
			foreach ($cartItems as $item) {
				if($productZip == $item->getZipcode()){
					$productZip = $item->getZipcode();
				}else{
					$productZip = $item->getZipcode();
				}
			}
		 ?> 
		  
		  var zipvalidate = '<?php echo $productZip  ?>';
		  <?php $zipcodemsg =  Mage::getStoreConfig('configuration/configuration_checkout_zipcode_validation/checkoutzipcode'); ?>
		  var zipcodemsg = '<?php echo $zipcodemsg ?>';
		  var finalmnsg =  zipcodemsg.replace('{{old_pincode}}',zipvalidate).replace('{{new_pincode}}',zip);
		  if(zipvalidate == selectedBillingPincode)
		  {
			  billing.save();
		  }
		  else
		  {
			  alert(finalmnsg);
			  return false;  
		  }
		  
   		var city = jQuery(".city").val();
   		var state = jQuery(".state").val();
		
		var cityLower = city.toLowerCase();
   		
   		
   	    /* full address condition start */
   		var full_address_value = jQuery('#billing-address-select option:selected').text();
   		full_address_value = full_address_value.toLowerCase();
   		/* full address condition end */
   		
   		if(full_address_value != 'new address' && full_address_value != "")
   		{
			if(full_address_value.indexOf('bangalore') > -1 || full_address_value.indexOf('bangaluru') > -1 || full_address_value.indexOf('bengaluru') > -1 || full_address_value.indexOf('mysore') > -1 || full_address_value.indexOf('mysuru') > -1)
			{
				if(full_address_value.indexOf('karnataka') > -1)
				{
				billing.save();
				}
				   else
				{
				alert("Currently delivering in Bangalore & Mysore only.");
				}				
			}
			else
			{
				alert("Currently delivering in Bangalore & Mysore only.");	
			}			
   		}
           
	    else	
	    {			
   		   		
			if(cityLower == 'bangalore' ||  cityLower == 'bangaluru' ||  cityLower == 'bengaluru' || cityyLower == 'mysore' || cityyLower == 'mysuru')
			{
				
				if(state == 501)
				{
					var zipcodestart= 560000;
					var zipcodeend = 560300;
					var zipcodekVal = jQuery("#zip").val();
					if((zipcodekVal > zipcodestart && zipcodekVal < zipcodeend)) {		
						     	
					var hasError1 = false; 
					var mobiReg = /^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[789]\d{9}$/;
					//var mobiReg1 = /^(?:[2-9][0-8][0-9])(?!(\d)\1+$)([2-9][0-9]{2}[0-9]{4})$/;
					jQuery(".error1").hide();	
					var mobileVal = jQuery(".mobile").val();
				
			 
					if(mobileVal == '') {
						jQuery(".mobile").after('<span class="error1">Enter Mobile Number.</span>');
						hasError1 = true;
					}
		   
					else if(!mobiReg.test(mobileVal)) {
						jQuery(".mobile").after('<span class="error1">Enter Valid Mobile Number.</span>');
						hasError1 = true;
					}
					else
					{
					jQuery(".error1").hide();	
					}
					 
					 
							jQuery(".error2").hide();
							var hasError2 = false;
							
							var zipvalidate =/^[0-9]{6}$/;
					
							if(zipcodekVal == '') {
								jQuery("#zip").after('<span class="error2">Enter Zip Code.</span>');
								hasError2 = true;
							}
							
							if(!zipvalidate.test(zipcodekVal)) {
								jQuery("#zip").after('<span class="error2">Enter Valid Zip Code.</span>');
								hasError2 = true;
							}
							
				
					 
							jQuery(".error3").hide();
								var hasError3 = false;
								var nameregex =/^[a-zA-Z. ]+$/;
								var nameaddressVal = jQuery(".myfirstname").val();
								if(!nameregex.test(nameaddressVal)) {
										jQuery(".myfirstname").after('<span class="error3">Enter Valid First Name.</span>');
										hasError3 = true;
							}else{
							jQuery(".error3").hide();	
							}
							jQuery(".error4").hide();
								var hasError4 = false;
								var addressregex =/^[a-zA-Z0-9\/\-.,#_ ]+$/i;
								var addressVal = jQuery(".street1").val();
								if(!addressregex.test(addressVal)) {
										jQuery(".street1").after('<span class="error4">Enter Valid Address.</span>');
										hasError4 = true;
							}
							else
							{
								jQuery(".error4").hide();	
							}
								
							jQuery(".error5").hide();
							var hasError5 = false;
							var lnameregex =/^[a-zA-Z. ]+$/;
							var lnameaddressVal = jQuery(".mysecname").val();
							if(!lnameregex.test(lnameaddressVal)) {
									jQuery(".mysecname").after('<span class="error5">Enter Valid Last Name.</span>');
									hasError5 = true;
								}
								else{
								jQuery(".error5").hide();	
								}
								
								
							
							var address2Valemty = jQuery(".street2").val();
							if(!address2Valemty == ''){
								
								
								
						
								jQuery(".error6").hide();
									var hasError6 = false;
									var address2regex = /^[a-zA-Z0-9\/\-.,#_ ]+$/i;
									var address2Val = jQuery(".street2").val();
									if(!address2regex.test(address2Val)) {
											jQuery(".street2").after('<span class="error6">Enter Valid Address.</span>');
											hasError6 = true;
								}
								else
								{
								jQuery(".error6").hide();	
								}
								if(hasError6 == true) { return false; }
							}
	   
						
					 
					 if(hasError1 == true)
					 {
						return false; 
					 }
					 else if(hasError2 == true)
					 {
						return false;
					 }
					 else if(hasError3 == true)
					 {
						return false;
					 }
					 else if(hasError4 == true)
					 {
						return false;
					 }
					 else if(hasError5 == true)
					 {
						return false;
					 }
					 else
					 {
					 billing.save();		 
					 }
					 
					}
					else
					{
						alert("Currently delivering in Bangalore & Mysore only.");	
					}
				
				}
				
			    else
				{
					alert("Currently delivering in Bangalore & Mysore only.");	
				}				
   			
   			}
		    else
   			{
   				alert("Currently delivering in Bangalore & Mysore only.");	
   			}
   
		} //Mani end			
   					
   				
   	}
   	
   	
   	
   	
   	else
   	{
   		var hasError1 = false; 
   			var mobiReg = /^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[789]\d{9}$/;
   			//var mobiReg1 = /^(?:[2-9][0-8][0-9])(?!(\d)\1+$)([2-9][0-9]{2}[0-9]{4})$/;
   			jQuery(".error1").hide();	
   			var mobileVal = jQuery(".mobile").val();
   		 
   			if(mobileVal == '') {
   				jQuery(".mobile").after('<span class="error1">Enter mobile number.</span>');
   				hasError1 = true;
   			}
   
   			else if(!mobiReg.test(mobileVal)) {
   				jQuery(".mobile").after('<span class="error1">Enter Valid Mobile Number.</span>');
   				hasError1 = true;
   			}
   			else
   			{
   			jQuery(".error1").hide();	
   			}
   				 
   				 
   						jQuery(".error2").hide();
   						var hasError2 = false;
   						var zipcodestart= 560000;
   						var zipcodeend = 560300;
   						
   						var zipcodekVal = jQuery("#zip").val();
						var zipvalidate =/^[0-9]{6}$/;
						
   						if(zipcodekVal == '') {
   							jQuery("#zip").after('<span class="error2">Enter Zip Code.</span>');
   							hasError2 = true;
   						}
   						else if(!zipvalidate.test(zipcodekVal)) {
								jQuery("#zip").after('<span class="error2">Enter Valid Zip Code.</span>');
								hasError2 = true;
						}
   						
   						   			
   			
   				 
   						jQuery(".error3").hide();
   							var hasError3 = false;
   							var nameregex =/^[a-zA-Z. ]+$/;
   							var nameaddressVal = jQuery(".myfirstname").val();
   							if(!nameregex.test(nameaddressVal)) {
   									jQuery(".myfirstname").after('<span class="error3">Enter Valid First Name.</span>');
   									hasError3 = true;
   						}else{
   						jQuery(".error3").hide();	
   						}
   						jQuery(".error4").hide();
   							var hasError4 = false;
   							var addressregex = /^[a-zA-Z0-9\/\-.,#_ ]+$/i;
   							
   							var addressVal = jQuery(".street1").val();
   							if(!addressregex.test(addressVal)) {
   									jQuery(".street1").after('<span class="error4">Enter Valid Address.</span>');
   									hasError4 = true;
   						}
   						else
   						{
   							jQuery(".error4").hide();	
   						}
   							
   						jQuery(".error5").hide();
   						var hasError5 = false;
   						var lnameregex =/^[a-zA-Z. ]+$/;
   						var lnameaddressVal = jQuery(".mysecname").val();
   						if(!lnameregex.test(lnameaddressVal)) {
   								jQuery(".mysecname").after('<span class="error5">Enter Valid Last Name.</span>');
   								hasError5 = true;
   							}
   							else{
   							jQuery(".error5").hide();	
   							}
   						
   						
   				
   						var address2Valemty = jQuery(".street2").val();
   						if(!address2Valemty == ''){
   							
   						
   							jQuery(".error6").hide();
   								var hasError6 = false;
   								var address2regex = /^[a-zA-Z0-9\/\-.,#_ ]+$/i;
   								var address2Val = jQuery(".street2").val();
   								if(!address2regex.test(address2Val)) {
   										jQuery(".street2").after('<span class="error6">Enter Valid Address.</span>');
   										hasError6 = true;
   							}
   							else
   							{
   							jQuery(".error6").hide();	
   							}
   							if(hasError6 == true) { return false; }
   						}
   
   			  
   
   					
   				 
   				 if(hasError1 == true)
   				 {
   					return false; 
   				 }
   				 else if(hasError2 == true)
   				 {
   					return false;
   				 }
   				 else if(hasError3 == true)
   				 {
   					return false;
   				 }
   				 else if(hasError4 == true)
   				 {
   					return false;
   				 }
   				 else if(hasError5 == true)
   				 {
   					return false;
   				 }
   				 else
   				 {
   				 billing.save();		 
   				 }		 
   	}	
   		
   });
</script>
