<ul class="nav nav-tabs cpaymenttab" role="tablist">
    <li role="presentation" class="active"><a href="#Address" aria-controls="home" role="tab" data-toggle="tab5">Address</a></li>
    <li role="presentation"><a href="#Confirm" aria-controls="profile" role="tab" data-toggle="tab5">Confirm</a></li>
    <li role="presentation"><a href="#Payment" aria-controls="messages" role="tab" data-toggle="tab5">Payment</a></li>
    <li role="presentation"><a href="#Complete" aria-controls="settings" role="tab" data-toggle="tab5">Complete</a></li>
  </ul>