<?php
    $columns = $this->getColumns();
?>
<ul class="products-grid">

  <?php if (count($this->getItems())): ?>
    <?php foreach ($this->getItems() as $item): ?>
       <li class="col-lg-4 col-md-4 col-sm-4 col-xs-12  image-wrapper item first">

       
		<a href="<?php echo $this->getUrl('wishlist/index/remove/item/' . $item->getId() . '/'); ?>" class="btn-remove btn-remove2 fa fa-times"></a>


        <?php foreach ($columns as $column): ?>

          <?php $column->setItem($item); echo $column->toHtml($item);?>
        <?php endforeach; ?>
      </li>
    <?php endforeach; ?>
  <?php else: ?>
    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-12  image-wrapper item first">
      <div colspan="<?php echo count($columns);?>" class="wishlist-empty"><?php echo $this->__('This Wishlist has no Items');?></div>
    </li>
  <?php endif; ?>
    
</ul>