<?php
/* 
 * @category    Clarion
 * @package     Clarion_PaymentModulePack
 * @created     15th Dec,2014
 * @author      Clarion magento team<magento.team@clariontechnologies.co.in>   
 * @purpose     Redirect page template
 * @copyright   Copyright (c) 2014 Clarion Technologies Pvt.Ltd
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License
 */
?>

<?php
// Get Custom card Details
$customcard = Mage::registry( 'customcard' );
?>

<p>Redirecting... If you have been here for a while, please <a href="#">click here</a>.</p>
<p>Make sure you don't press the 'Back' button in your browser till your order is complete.</p>

<form name="customcardform" method="post" action="<?php echo $customcard['action']; ?>">
	<input type="hidden" name="Merchant_Id" value="<?php echo $customcard['merchant_id']; ?>">
	<input type="hidden" name="Amount" value="<?php echo $customcard['amount']; ?>">
	<input type="hidden" name="Order_Id" value="<?php echo $customcard['order_id']; ?>">
	<input type="hidden" name="Redirect_Url" value="<?php echo $customcard['redirect_url']; ?>">
	<input type="hidden" name="billing_cust_name" value="<?php echo $customcard['billing_cust_name']; ?>"> 
	<input type="hidden" name="billing_cust_address" value="<?php echo $customcard['billing_cust_address']; ?>"> 
	<input type="hidden" name="billing_cust_country" value="<?php echo $customcard['billing_cust_country']; ?>"> 
	<input type="hidden" name="billing_cust_state" value="<?php echo $customcard['billing_cust_state']; ?>"> 
	<input type="hidden" name="billing_zip" value="<?php echo $customcard['billing_zip']; ?>"> 
	<input type="hidden" name="billing_cust_tel" value="<?php echo $customcard['billing_cust_tel']; ?>"> 
	<input type="hidden" name="billing_cust_email" value="<?php echo $customcard['billing_cust_email']; ?>"> 
	<input type="hidden" name="delivery_cust_name" value="<?php echo $customcard['delivery_cust_name']; ?>"> 
	<input type="hidden" name="delivery_cust_address" value="<?php echo $customcard['delivery_cust_address']; ?>"> 
	<input type="hidden" name="delivery_cust_country" value="<?php echo $customcard['delivery_cust_country']; ?>"> 
	<input type="hidden" name="delivery_cust_state" value="<?php echo $customcard['delivery_cust_state']; ?>"> 
	<input type="hidden" name="delivery_cust_tel" value="<?php echo $customcard['delivery_cust_tel']; ?>"> 
	<input type="hidden" name="billing_cust_notes" value="<?php echo $customcard['billing_cust_notes']; ?>"> 
	<input type="hidden" name="Merchant_Param" value="<?php echo $customcard['merchant_param']; ?>"> 
	<input type="hidden" name="billing_cust_city" value="<?php echo $customcard['billing_city']; ?>"> 
	<input type="hidden" name="billing_zip_code" value="<?php echo $customcard['billing_zip']; ?>"> 
	<input type="hidden" name="delivery_cust_city" value="<?php echo $customcard['delivery_city']; ?>"> 
	<input type="hidden" name="delivery_zip_code" value="<?php echo $customcard['delivery_zip']; ?>"> 
</form>

<script type="text/javascript">
document.customcardform.submit();
</script>