<?php /** @var Klevu_Search_Block_Adminhtml_Wizard_Configure_User $this */ ?>
<?php echo $this->getChildHtml('messages') ?>
<form id="klevu_search_wizard_configure_user_form" action="<?php echo $this->getFormActionUrl() ?>" method="POST">
    <input type="hidden" name="form_key" value="<?php echo $this->getFormKey() ?>" />
    <fieldset class="fieldset">
        <table cellspacing="0" class="form-list" style="width:100%;">
            <tbody>
                <tr>
                    <td>
                        <table class="klevu_signup_form">
                            <tr>
                                <td colspan="2">
                                    <div class="content-header">
                                        <h3>Register New User</h3>
                                    </div>
                                    <p><?php echo $this->__("Fill out the form below to create a new Klevu user to use with this Magento installation:") ?></p>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label for="klevu_new_email"><?php echo $this->__("Primary Email:") ?><span class="required">&nbsp;<em>*</em></span></label>
                                </td>
                                <td class="value">
                                    <input type="text" name="klevu_new_email" id="klevu_new_email" class="required-entry input-text" />
                                    <p class="note">For login and technical support</p>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label for="merchantEmail"><?php echo $this->__("Retailer Email:") ?><span class="required">&nbsp;<em>*</em></span></label></td>
                                <td class="value">
                                    <input type="text" name="merchantEmail" id="merchantEmail" class="input-text" />
                                    <p class="note">
                                        For search insights and billing
                                    </p>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label for="klevu_new_password"><?php echo $this->__("Password:") ?><span class="required">&nbsp;<em>*</em></span></label></td>
                                <td class="value"><input type="password" name="klevu_new_password" id="klevu_new_password" class="input-text" />
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label for="userPlan"><?php echo $this->__("Choose Your  Solution:") ?><span class="required">&nbsp;<em>*</em></span></label></td>
                                <td class="value">
                                    <table cellpadding="3" cellspacing="0">
                                        <tr>
                                            <td><input type="radio" name="userPlan" value="free">&nbsp;Klevu BASIC&nbsp;&nbsp;&nbsp;</td>
                                            <td><input type="radio" name="userPlan" value="trial">&nbsp;Klevu PRO&nbsp;&nbsp;&nbsp;</td>
                                            <td><input type="radio" name="userPlan" value="partnerAccount">&nbsp;Klevu Partner</td>
                                        </tr>
                                    </table>
                                    <table>
                                        <tr>
                                            <td colspan="2" style="padding-top:5px;"><img  src="http://www.klevu.com/magento-screens/klevu-mage-package.jpg" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <p class="note" style="width:auto !important;"><a href="#" onClick="checkplan();" style="font-size:11px;">Learn more about BASIC v/s PRO </a></p>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="2">
                                                <p style="width:auto !important;">Please select Klevu partner option</br>if you are an authorized Klevu partner.</p>
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label for="contactNo"> <?php echo $this->__("Phone Number:") ?><span class="required">&nbsp;</span></label></td>
                                <td class="value"><input type="text" placeholder="Country code" name="countyCode" id="countyCode" class="input-text" value="<?php echo $this->getCountyCode() ?>" /> <input type="text" name="contactNo" id="contactNo" class="input-text" value="<?php echo $this->getContactNo() ?>" /></td>
                            </tr>
                            <tr>
                                <td class="label"><label for="klevu_new_url"> <?php echo $this->__("Store URL:") ?><span class="required">&nbsp;<em>*</em></span></label></td>
                                <td class="value"><input type="text" name="klevu_new_url" id="klevu_new_url" class="input-text" value="<?php echo $this->getStoreUrl() ?>" /></td>
                            </tr>
                            <tr>
                                <td class="label"></td>
                                <td class="value" style="padding-right: 26px;">
                                    <div class="button-set">
                                        <button type="submit"><span><?php echo $this->__("Register") ?></span></button>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </td>
                    <td>
                        <table class="klevu_signup_form">
                            <tr>
                                <td colspan="2">
                                    <div class="content-header">
                                        <h3>Already Registered?</h3>
                                    </div>
                                    <p><?php echo $this->__("If you have an account with Klevu, please log in:") ?></p>
                                </td>
                            </tr>
                            <tr>
                                <td class="label"><label for="klevu_existing_email"><?php echo $this->__("Primary Email:") ?><span class="required">&nbsp;<em>*</em></span></label></td>
                                <td class="value"><input type="text" name="klevu_existing_email" id="klevu_existing_email" class="input-text" /></td>
                            </tr>
                            <tr>
                                <td class="label"><label for="klevu_existing_password"><?php echo $this->__("Password:") ?><span class="required">&nbsp;<em>*</em></span></label></td>
                                <td class="value"><input type="password" name="klevu_existing_password" id="klevu_existing_password" class="input-text" /></td>
                            </tr>
                            <tr>
                                <td class="label"></td>
                                <td class="value">
                                    <div class="button-set">
                                        <button type="submit"><span><?php echo $this->__("Login") ?></span></button>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </fieldset>
</form>