<?php $_code=$this->getMethodCode() ?>
 <div class="cq_dd_payment">
            <p class="p_text">1. Write a cheque/DD with below given details.</p>
            <div class="pay_box"><span class="name">Pay to/ In Favour of :</span> <span class="details">mSupply</span>
                <span class="name">Date:</span> <span class="details">Today’s Date</span>
                <span class="name">Amount.:</span> <span class="details">662.00</span>
            </div>
            <p class="p_text"><span>Note:</span><b> Post dated cheques are not accepted.</b></p>
            <p class="p_text">2. Enter the details below</p>
<div>
   
         <input type="text" placeholder="*<?php echo $this->__('Cheque No#') ?>" title="<?php echo $this->__('Check No#') ?>" class="input-text required-entry validate-number Cheque_no" id="<?php echo $_code ?>_check_no" name="payment[check_no]" value="<?php echo $this->htmlEscape($this->getInfoData('check_no')) ?>" />
      

      <!--<div class="our-dd col-lg-6 col-md-6 col-sm-6 col-xs-12">
         <div class="our-dd-local col-lg-6 col-md-6 col-sm-6 col-xs-12 mt10">
            <input class="radio custom-cq-radio" type="radio" id="<?php echo $_code ?>_cheqloc" name="payment[cheqloc]" value="1" /> <span>Local Cheque</span>
         </div>
         <div class="our-dd-out col-lg-6 col-md-6 col-sm-6 col-xs-12 mt10">
            <input class="radio custom-cq-radio" type="radio" id="<?php echo $_code ?>_cheqloc" name="payment[cheqloc]" value="2" /> <span>Outstation Cheque</span>
         </div>
      </div>

      <span class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
         <input  class="mydate input-text required-entry" name="payment[check_date]" value="<?php echo $this->htmlEscape($this->getInfoData('check_date')) ?>" id="<?php echo $_code ?>_check_date" placeholder="*<?php echo $this->__('Cheque Date(mm/dd/yy):') ?>" title="<?php echo $this->__('Cheque Date(mm/dd/yy):') ?>" readonly type="text">
         
         <script type="text/javascript">
            var $a = jQuery.noConflict();
            //<![CDATA[
            // Calendar.setup({
            // inputField: "<?php echo $_code ?>_check_date",
            // ifFormat: "%m/%e/%Y",
            // showsTime: false,
            // button: "shipping_arrival_date_trig",
            // align: "Bl",
            // disableFunc: function(date) {
            // var now= new Date();
            // if(date.getFullYear() < now.getFullYear()) { return true; }
            // if(date.getFullYear() == now.getFullYear()) { if(date.getMonth() < now.getMonth()) { return true; } }
            // if(date.getMonth() == now.getMonth()) { if(date.getDate() < now.getDate()) { return true; } }
            // },
            // singleClick : true
            // });
            //]]>
            
            
            jQuery(function() {
               jQuery( "#<?php echo $_code ?>_check_date" ).datepicker({
                  minDate: 0 // 0 days offset = today
               });
            });
            
            
            jQuery("#<?php echo $_code ?>_check_date").on("click", function() {
               jQuery("#<?php echo $_code ?>_check_date").datepicker("show");
            });
                     
         </script>
      </span>

      <span class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
         <input type="text" placeholder="*<?php echo $this->__('PAN Number ') ?>" title="<?php echo $this->__('PAN Number ') ?>" class="input-text required-entry" id="<?php echo $_code ?>_panno" name="payment[panno]" value="<?php echo $this->htmlEscape($this->getInfoData('panno')) ?>" />
      </span>

      <span class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
         <input type="text" placeholder="*<?php echo $this->__('Drawee Name') ?>" title="<?php echo $this->__('Drawee Name') ?>" class="input-text required-entry" id="<?php echo $_code ?>_draweename" name="payment[draweename]" value="<?php echo $this->htmlEscape($this->getInfoData('draweename')) ?>" />
      </span>

      <script type="text/javascript">
         //<![CDATA[
         // Calendar.setup({
         // inputField: "_dob",
         // ifFormat: "%m/%e/%y",
         // showsTime: false,
         // button: "_dob_trig",
         // align: "B1",
         // singleClick: true
         // });
         //]]>
      </script>-->
 
         <input type="text" placeholder="*<?php echo $this->__('Drawee Bank') ?>" title="<?php echo $this->__('Drawee Bank') ?>" class="input-text required-entry bank_name" id="<?php echo $_code ?>_draweebank" name="payment[draweebank]" value="<?php echo $this->htmlEscape($this->getInfoData('draweebank')) ?>" />
     
      <?php echo $this->getMethod()->getConfigData('message');?>
 <div class="btn_wrapper">
                <div class="trms-cndts"> By placing the order, I have read and agreed to msupply.com <br/> <span class="terms-conditions"> Terms Use | Terms of Sale </span></div>
            </div>
</div>
