<?php
/* 
 * @category    Clarion
 * @package     Clarion_PaymentModulePack
 * @created     12th Dec,2014
 * @author      Clarion magento team<magento.team@clariontechnologies.co.in>   
 * @purpose     Cheque payment template with cheque number and date parameters
 * @copyright   Copyright (c) 2014 Clarion Technologies Pvt.Ltd
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License
 */
?>
<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">

	  <li>
        <label for="<?php echo $_code ?>_check_no" class="required"><em>*</em><?php echo $this->__('Cheque No#') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('Check No#') ?>" class="input-text required-entry validate-number" id="<?php echo $_code ?>_check_no" name="payment[check_no]" value="<?php echo $this->htmlEscape($this->getInfoData('check_no')) ?>" />
        </span>
    </li>
    <li>
        <label for="<?php echo $_code ?>_check_date" class="required"><em>*</em><?php echo $this->__('Cheque Date:') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('Check Date:') ?>" class="input-text required-entry" id="_dob" name="payment[check_date]" value="<?php echo $this->htmlEscape($this->getInfoData('check_date')) ?>"/>
			<img width="30" height="25" style="display: inline; padding-left: 5px;position:absolute;" title="<?php echo $this->__('Check Date:') ?>" id="_dob_trig" class="v-middle" alt="" src="<?php echo $this->getSkinUrl('images/calendar.gif');?>">
        </span>
<script type="text/javascript">
//<![CDATA[
	Calendar.setup({
		inputField: "_dob",
		ifFormat: "%m/%e/%y",
		showsTime: false,
		button: "_dob_trig",
		align: "B1",
		singleClick: true
	});
	//]]>
</script>
    </li>
	<li>
        <label for="<?php echo $_code ?>_draweename" class="required"><em>*</em><?php echo $this->__('Drawee Name') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('Bank Name') ?>" class="input-text required-entry" id="<?php echo $_code ?>_draweename" name="payment[draweename]" value="<?php echo $this->htmlEscape($this->getInfoData('draweename')) ?>" />
        </span>
    </li>
 <li>
        <label for="<?php echo $_code ?>_draweebank" class="required"><em>*</em><?php echo $this->__('Drawee Bank') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('IFSC Code') ?>" class="input-text required-entry" id="<?php echo $_code ?>_draweebank" name="payment[draweebank]" value="<?php echo $this->htmlEscape($this->getInfoData('draweebank')) ?>" />
        </span>
    </li>
  <li>
		<label class="radio" for="<?php echo $_code ?>_cheqloc">Preferred Location for Cheque</label>
      <input class="radio" type="radio" id="<?php echo $_code ?>_cheqloc" name="payment[cheqloc]" value="1" /> <span>Local Cheque</span>
	  <input class="radio" type="radio" id="<?php echo $_code ?>_cheqloc" name="payment[cheqloc]" value="2" /> <span>Outstation Cheque</span>
    </li>
<li>
        <label for="<?php echo $_code ?>_panno" class="required"><em>*</em><?php echo $this->__('PAN Number ') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('IFSC Code') ?>" class="input-text required-entry" id="<?php echo $_code ?>_panno" name="payment[panno]" value="<?php echo $this->htmlEscape($this->getInfoData('panno')) ?>" />
        </span>
    </li>
	
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
