<div class="know_more">
            <h3>Do u Know ?</h3>
            <div class="clearfix"></div>
       
            <div class="fadein"><p id="changeText"></p></div>
            <div class="clearfix"></div>
            <h2>Want to know more ?</h2>
            <form role="form">
              <input type="text" placeholder="Name" />
              <input type="text" placeholder="Phone" />
              <input type="text" placeholder="Email" />
              <textarea title="qus" placeholder="Ask Qus"></textarea>
            <button type="submit" class="know_more_btn">Ask Now</button>
</form>