
<!-- new code-->
<div class="wrapper-container">
    <!-- left side-->
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 rpad0">
        <div class="well-block">

            <div class="stl-img"><img class="img-responsive" src="<?php echo $this->getSkinUrl('images/plumbing.png'); ?>" alt="plumbing">
            </div>
            <div class="comment">
                <div class="steelheading">CPVC Pipes</div>
                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
            </div>
        </div>
    </div>
    <!-- well block end-->
    <!-- left side-->
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 customrpad5">

        <!-- select filters-->
        <div class="well-block">

            <div class="row">
                <div class="col-lg-12">
                    <div class="cbheading">Select Filters</div>
                    <div class="syellowline"></div>
                </div>
            </div>
            <div class="row mb1em">
                <div class="col-lg-2">
                    <h5 class="text-center">Type</h5>
                </div>
				
				<!-- standard
				
				 <div class="col-lg-10">
                    <div class="p-brandtype col-lg-3 col-sm-4 mb1em">
                        <label class="btn_ptype">CPVC</label>
                    </div>
                    <div class="p-brandtype col-lg-3 col-sm-4 mb1em">
                        <label class="btn_ptype">CPVC</label>
                    </div>
                    <div class="p-brandtype col-lg-3 col-sm-4 mb1em">
                        <label class="btn_ptype">CPVC</label>
                    </div>
                    <div class="p-brandtype col-lg-3 col-sm-4 mb1em">
                        <label class="btn_ptype">CPVC</label>
                    </div>
                    <div class="p-brandtype col-lg-3 col-sm-4 mb1em">
                        <label class="btn_ptype">CPVC</label>
                    </div>
                    <div class="p-brandtype col-lg-3 col-sm-4 mb1em">
                        <label class="btn_ptype">CPVC</label>
                    </div>
                    <div class="p-brandtype col-lg-3 col-sm-4 mb1em">
                        <label class="btn_ptype">CPVC</label>
                    </div>
                    <div class="p-brandtype col-lg-3 col-sm-4 mb1em">
                        <label class="btn_ptype">CPVC</label>
                    </div>
                </div>
				
				end -->
				
				
                <div class="col-lg-10">
                    <div class="p-brandtype">
                        <label class="btn_ptype">CPVC</label>
                    </div>
                    <div class="p-brandtype">
                        <label class="btn_ptype">PVC</label>
                    </div>
                    <div class="p-brandtype">
                        <label class="btn_ptype">UPVC</label>
                    </div>
                    <div class="p-brandtype">
                        <label class="btn_ptype">SWR</label>
                    </div>
                    <div class="p-brandtype">
                        <label class="btn_ptype">PPRC</label>
                    </div>
                    <div class="p-brandtype">
                        <label class="btn_ptype">Chamber</label>
                    </div>
                    <div class="p-brandtype">
                        <label class="btn_ptype">HDPE</label>
                    </div>
                    <div class="p-brandtype">
                        <label class="btn_ptype">ASTM</label>
                    </div>
					<div class="p-brandtype">
                        <label class="btn_ptype">Borewell and Casing</label>
                    </div>
                </div>
            </div>

            <div class="row mb1em">
                <div class="col-lg-2">

                </div>
                <div class="col-lg-10 pad0">
                    <div class="p-brandtype col-lg-3 col-sm-6">
                        <input type="radio" value="" /><span class="ml5">Ring Type</span>
                    </div>
                    <div class="p-brandtype col-lg-3 col-sm-6">
                        <input type="radio" value="" /><span class="ml5">Solvent Type</span>
                    </div>

                </div>
            </div>

            <div class="row mb1em">
                <div class="col-lg-2">
                    <h5 class="text-center">Diameter</h5>
                </div>
                <div class="col-lg-10 pad0">
                    <div class="col-lg-3 col-sm-6 input-box">
                       <select>
                            <option>1</option>
                            <option>1</option>
                            <option>1</option>
                        </select>
                    </div>
                    <div class="col-lg-3 col-sm-6 input-box">
                        <select>
                            <option>1</option>
                            <option>1</option>
                            <option>1</option>
                        </select>
                    </div>
                    <div class="col-lg-3">
                        <h5 class="text-center">Standard</h5>
                    </div>
                    <div class="col-lg-3 input-box">
                        <select>
                            <option>1</option>
                            <option>1</option>
                            <option>1</option>
                        </select>
                    </div>

                </div>
            </div>

            <div class="col-lg-6 col-lg-offset-3 text-center">
                <button class="btn_pupdate">UPDATE</button>
            </div>


        </div>
        <!-- well block end-->
        <!-- select filters end-->

        <!-- select pipes-->
        <div class="well-block">

            <div class="row clear">
                <div class="col-lg-12">
                    <div class="cbheading">Select Pipes</div>
                    <div class="syellowline"></div>
                </div>


            </div>

            <div class="table-responsive wid100 m1em0">
                <table class="table table-condensed pipestable">


                    <thead>
                        <tr>
                            <th>Product</th>
                            <th></th>
                            <th>Length</th>
                            <th>Unit Price</th>
                            <th></th>

                        </tr>
                    </thead>
                    <tbody>

                        <tr class="cust-trb">
                            <td width="45%">Mohan Steel Corporation (10000052)</td>
                            <td width="5%"><i class="fa fa-info-circle cinfo"></i>
                            </td>
                            <td width="15%">12Mtr</td>
                            <td width="20%">123</td>
                            <td width="15%">
                                <button class="btn_padd">+ ADD</button>
                            </td>
                        </tr>
                        <tr class="cust-trb">
                            <td width="45%">Mohan Steel Corporation (10000052)</td>
                            <td width="5%"><i class="fa fa-info-circle cinfo"></i>
                            </td>
                            <td width="15%">12Mtr</td>
                            <td width="20%">123</td>
                            <td width="15%">
                                <button class="btn_padd">+ ADD</button>
                            </td>
                        </tr>
                        <tr class="cust-trb">
                            <td width="45%">Mohan Steel Corporation (10000052)</td>
                            <td width="5%"><i class="fa fa-info-circle cinfo"></i>
                            </td>
                            <td width="15%">12Mtr</td>
                            <td width="20%">123</td>
                            <td width="15%">
                                <button class="btn_padd">+ ADD</button>
                            </td>
                        </tr>
                        <tr class="cust-trb">
                            <td width="45%">Mohan Steel Corporation (10000052)</td>
                            <td width="5%"><i class="fa fa-info-circle cinfo"></i>
                            </td>
                            <td width="15%">12Mtr</td>
                            <td width="20%">123</td>
                            <td width="15%">
                                <button class="btn_padd">+ ADD</button>
                            </td>
                        </tr>
                    </tbody>

                </table>
            </div>

            <!-- fittings-->
            <div class="row clear">
                <div class="col-lg-12">
                    <div class="cbheading">Select Related Fittings (For 1/2" Diameter)</div>
                    <div class="syellowline"></div>
                </div>


            </div>

            <div class="table-responsive wid100 m1em0">
                <table class="table table-condensed pipestable">


                    <thead>
                        <tr>
                            <th>Product</th>
                            <th></th>
                            <th>Type</th>
                            <th>Unit Price</th>
                            <th></th>

                        </tr>
                    </thead>
                    <tbody>

                        <tr class="cust-trb">
                            <td width="45%"><img width="30" class="mr10" src="<?php echo $this->getSkinUrl('images/pipes.png'); ?>">Mohan Steel Corporation (10000052)</td>
                            <td width="5%"><i class="fa fa-question-circle cqtn"></i>
                            </td>
                            <td width="15%">12Mtr</td>
                            <td width="20%">123</td>
                            <td width="15%">
                                <button class="btn_padd">+ ADD</button>
                            </td>
                        </tr>
                        <tr class="cust-trb">
                            <td width="45%"><img width="30" class="mr10" src="<?php echo $this->getSkinUrl('images/plumbing.png'); ?>">Mohan Steel Corporation (10000052)</td>
                            <td width="5%"><i class="fa fa-question-circle cqtn"></i>
                            </td>
                            <td width="15%">12Mtr</td>
                            <td width="20%">123</td>
                            <td width="15%">
                                <button class="btn_padd">+ ADD</button>
                            </td>
                        </tr>
                        <tr class="cust-trb">
                            <td width="45%"><img width="30" class="mr10" src="<?php echo $this->getSkinUrl('images/pipes.png'); ?>">Mohan Steel Corporation (10000052)</td>
                            <td width="5%"><i class="fa fa-question-circle cqtn"></i>
                            </td>
                            <td width="15%">12Mtr</td>
                            <td width="20%">123</td>
                            <td width="15%">
                                <button class="btn_padd">+ ADD</button>
                            </td>
                        </tr>
                        <tr class="cust-trb">
                            <td width="45%"><img width="30" class="mr10" src="<?php echo $this->getSkinUrl('images/plumbing.png'); ?>">Mohan Steel Corporation (10000052)</td>
                            <td width="5%"><i class="fa fa-question-circle cqtn"></i>
                            </td>
                            <td width="15%">12Mtr</td>
                            <td width="20%">123</td>
                            <td width="15%">
                                <button class="btn_padd">+ ADD</button>
                            </td>
                        </tr>
                    </tbody>

                </table>
            </div>
            <!-- fitings end-->





        </div>
        <!-- well block end-->
        <!-- select pipes end-->

    </div>
    <!-- left side end-->


    <div class="col-lg-4 col-sm-4 col-md-4 col-xs-12 customlpad4">
        <!-- choose brand-->
        <div class="well-block mb0">
            <div class="cbheading" id="cbheading">Choose a Brand</div>
            <div class="syellowline"></div>
            <div class="row clear">


                <div class="col-lg-6 col-xs-12 col-sm-12 col-md-6 mcbrand ">
                    <input checked="checked" class="brand_list" name="brand" id="deal1871" value="1871" type="radio"><span class="mbrandname">A-one gold</span>
                </div>



                <div class="col-lg-6 col-xs-12 col-sm-12 col-md-6 mcbrand ">
                    <input class="brand_list" name="brand" id="deal345" value="345" type="radio"><span class="mbrandname">Bhuwalka</span>
                </div>



                <div class="col-lg-6 col-xs-12 col-sm-12 col-md-6 mcbrand ">
                    <input class="brand_list" name="brand" id="deal1869" value="1869" type="radio"><span class="mbrandname">Goplala</span>
                </div>



                <div class="col-lg-6 col-xs-12 col-sm-12 col-md-6 mcbrand ">
                    <input class="brand_list" name="brand" id="deal1486" value="1486" type="radio"><span class="mbrandname">Indus</span>
                </div>



                <div class="col-lg-6 col-xs-12 col-sm-12 col-md-6 mcbrand ">
                    <input class="brand_list" name="brand" id="deal354" value="354" type="radio"><span class="mbrandname">JSW</span>
                </div>



                <div class="col-lg-6 col-xs-12 col-sm-12 col-md-6 mcbrand ">
                    <input class="brand_list" name="brand" id="deal635" value="635" type="radio"><span class="mbrandname">Jindal</span>
                </div>



                <div class="col-lg-6 col-xs-12 col-sm-12 col-md-6 mcbrand ">
                    <input class="brand_list" name="brand" id="deal3326" value="3326" type="radio"><span class="mbrandname">Kamachi</span>
                </div>



                <div class="col-lg-6 col-xs-12 col-sm-12 col-md-6 mcbrand ">
                    <input class="brand_list" name="brand" id="deal253" value="253" type="radio"><span class="mbrandname">Kamadhenu</span>
                </div>



                <div class="col-lg-6 col-xs-12 col-sm-12 col-md-6 mcbrand ">
                    <input class="brand_list" name="brand" id="deal255" value="255" type="radio"><span class="mbrandname">Meenakshi</span>
                </div>



                <div class="col-lg-6 col-xs-12 col-sm-12 col-md-6 mcbrand ">
                    <input class="brand_list" name="brand" id="deal355" value="355" type="radio"><span class="mbrandname">Monnet</span>
                </div>


            </div>
        </div>
        <!-- well block end-->
        <!-- choose brand end-->



        <!-- choose brand-->
        <div class="well-block mb0">
            <div class="cbheading" id="cbheading">My List</div>
            <div class="syellowline"></div>
            <div class="row clear plumb-listbox">
                <div class="col-lg-3 col-xs-12 col-sm-3 col-md-3 pad0">
                    <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/plumbing.png'); ?>" alt="plumbing">
                </div>
				<div class="col-lg-6 col-xs-12 col-sm-6 col-md-6 pad0">
                    <div class="threedots list-phead">Bhuwalka CPVC Pipes</div>
					<div class="line2-head">solvent D-123 " Ltr</div>
					<div class="line3-pprice">₹284/unit</div>
					<div class="line2-head">
					<!-- input box-->
					<div class="wrap-qty">				
						<div class="qty-set">
							<span class="quantity-box">
								<input type="text" name="qty" value="1" class="quantity-input qty" />
								<input type="button" class="quantity-controls quantity-minus" value="-">
								<input type="button" class="quantity-controls quantity-plus" value="+">	
							</span>	
						</div>	
					</div>	
					<!-- end-->
					
					</div>
					
                </div>
				<div class="col-lg-3 col-xs-12 col-sm-3 col-md-3 pad0">
					<div class="list-remove"><a href="#" class="btn-premovelist fa fa-times"></a></div>
                    <div class="list-pprice">₹345332</div>
                </div>

            </div>
			
			<div class="row clear plumb-listbox">
                <div class="col-lg-3 col-xs-12 col-sm-3 col-md-3 pad0">
                    <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/plumbing.png'); ?>" alt="plumbing">
                </div>
				<div class="col-lg-6 col-xs-12 col-sm-6 col-md-6 pad0">
                    <div class="threedots list-phead">Bhuwalka CPVC Pipes</div>
					<div class="line2-head">solvent D-123 " Ltr</div>
					<div class="line3-pprice">₹284/unit</div>
					<div class="line2-head">
					<!-- input box-->
					<div class="wrap-qty">				
						<div class="qty-set">
							<span class="quantity-box">
								<input type="text" name="qty" value="1" class="quantity-input qty" />
								<input type="button" class="quantity-controls quantity-minus" value="-">
								<input type="button" class="quantity-controls quantity-plus" value="+">	
							</span>	
						</div>	
					</div>	
					<!-- end-->
					
					</div>
					
                </div>
				<div class="col-lg-3 col-xs-12 col-sm-3 col-md-3 pad0">
					<div class="list-remove"><a href="#" class="btn-premovelist fa fa-times"></a></div>
                    <div class="list-pprice">₹345332</div>
                </div>

            </div>
			
			<div class="row clear plumb-listbox">
                <div class="col-lg-3 col-xs-12 col-sm-3 col-md-3 pad0">
                    <img class="img-responsive" src="<?php echo $this->getSkinUrl('images/pipes.png'); ?>" alt="plumbing">
                </div>
				<div class="col-lg-6 col-xs-12 col-sm-6 col-md-6 pad0">
                    <div class="threedots list-phead">Bhuwalka CPVC Pipes</div>
					<div class="line2-head">solvent D-123 " Ltr</div>
					<div class="line3-pprice">₹284/unit</div>
					<div class="line2-head">
					<!-- input box-->
					<div class="wrap-qty">				
						<div class="qty-set">
							<span class="quantity-box">
								<input type="text" name="qty" value="1" class="quantity-input qty" />
								<input type="button" class="quantity-controls quantity-minus" value="-">
								<input type="button" class="quantity-controls quantity-plus" value="+">	
							</span>	
						</div>	
					</div>	
					<!-- end-->
					
					</div>
                </div>
				<div class="col-lg-3 col-xs-12 col-sm-3 col-md-3 pad0">
					<div class="list-remove"><a href="#" class="btn-premovelist fa fa-times"></a></div>
                    <div class="list-pprice">₹345332</div>
                </div>

            </div>
			
			<div class="row clear plumb-listbox">
				<div class="col-lg-6"><div class="list_subtotal">Sub Total</div></div>
				<div class="col-lg-6 pad0"><div class="list-totalprice">₹2132311.00</div></div>
			</div>
			
			<div class="col-lg-6 col-lg-offset-3 col-sm-offset-3 col-xs-12 col-md-offset-1 col-md-10 col-sm-6 list-btn">
				<button style="display: inline-block;" type="button" title="Add to List" class="btn_addplist addtocart">Add to List</button>
			</div>

        </div>
        <!-- well block end-->


        <!-- seller block-->

			<div class="seller_choosen" id="seller_choosen" style="">
			  <div class="well-block-seller">
				<div class="clearfix"></div>
				<div class="selectmsg1">
				  <div class="disptable">
					
					  <div class="pdt-rthead col-lg-12 col-md-12 col-sm-12 col-xs-12">Supplier</div>

					  <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7 top-selname pad0"><h4 id="seller">Sri Sambavanath Agency</h4></div>
					  <div class="totalseller col-lg-5 col-md-5 col-sm-5 col-xs-5 pad0"><h4><a href="#zipsearchresult" id="totalseller" style="text-transform:capitalize">Change Supplier</a></h4></div>
					  <div class="clearfix"></div>
					  <div class="col-lg-7 col-md-7 col-sm-7 col-xs-7 top-desp-time pad0"><h5> Dispatch in <span id="estimate">2-3 Days</span></h5></div>
					  <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5 top-desp-time pad0" style="text-align:right;"><h5 class="seller-num">(2 more Suppliers)</h5></div>
					
				  </div>
					
				</div>

				<div class="col-lg-6 col-lg-offset-3 col-sm-offset-3 col-xs-12 col-md-offset-1 col-md-10 col-sm-6 list-btn">
				    <button style="display: inline-block;" type="button" title="Check for Best Price" class="btn_chkbestprice">Check for Best Price</button>
				</div>
			  </div>
			</div>
        <!-- seller block end-->



    </div>
    <!-- right side end-->



    <!-- choose seller-->
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

        <div class="well-block" id="seller-result">
            <div class="csheading">Choose Seller</div>
            <div class="col-lg-12 rcustomline">
                <div class="csyellowline"></div>
            </div>
            <div class="area_pin">
                <!--area_pin start-->
                <div class="row mb1em">
                    <div class="col-lg-5 col-xs-12 col-md-6 col-sm-8 mt3em">
                        <div class="row">
                            <div class="col-lg-4 col-sm-6 col-xs-12 text-left mt10 rcheckavail">
                                <span class="glyphicon glyphicon-map-marker stlyellow mr10"></span><span>Check Availability</span>
                            </div>
                            <div class="col-lg-6 col-sm-6 col-xs-12 pad0 rcustompad">
                                <div class="input-group customzipcode">

                                    <input style="border: 1px solid rgb(204, 204, 204);" name="zip_input" value="560001" class="pin_input form-control" id="zip_input" placeholder="Enter Pincode" type="text">
                                    <span class="input-group-addon"><input id="search_by_zip" class="stlzip customgo" name="search_by_zip" value="CHECK" type="submit"></span>
                                </div>
                                <div style="display: none;" class="errmsg clearfix"></div>
                            </div>
                        </div>
                    </div>
                    <!-- col-4 end-->


                    <div class="col-lg-2 col-xs-12 col-md-3 col-sm-4 mt3em">

                    </div>
                    <div class="col-lg-5 col-xs-12 col-md-5 col-sm-5 mt3em text-right listseller-count" style="">
                        <div class="slrmsg"><span class="sellercount">4</span> Seller(s) found in Pincode <span class="ziplist">560001</span>
                        </div>

                    </div>

                </div>
                <!-- row end-->
            </div>
            <!--area_pin end-->




            <div class="select_seller">

                <div class="table-responsive wid100">
                    <table class="table table-condensed sellertable">


                        <thead>
                            <tr class="zipsearchHeading">
                                <th>Seller</th>
                                <th>Rating</th>
                                <th>Dispatch in</th>
                                <th>Min. Order Qty</th>
                                <th>Total Price</th>
                                <th></th>

                            </tr>
                        </thead>
                        <tbody class="zipsearchHeadingResult bdseller" id="zipsearchHeadingResult">

                            <tr class="clickmetoselect cust-trb">
                                <td>
                                    <div class="threedots">Mohan Steel Corporation (10000052)</div>
                                </td>
                                <td>
                                    <div class="rating"><span style="width:100%" class="ratingwidth">4.8</span><span class="ratingblank"></span>
                                    </div>
                                </td>
                                <td>1-2 Days</td>
                                <td>-</td>
                                <td class="seller_total1484">₹ 0.00</td>
                                <td>
                                    <input disable="disable" id="button-1484" value="select" class="selectvendor tick" sellerid="1484" for="radio-1" type="button">
                                    <input checked="checked" class="clickmetoselect1" style="display:none;margin:4px 7px 0 0" moq="-" seller-name="Mohan Steel Corporation" name="vendor" value="1484" id="radio-1484" type="radio">
                                </td>

                            </tr>
                            <tr class="clickmetoselect cust-trb">
                                <td>Shankara Infrastructure Materials Ltd (10000093)</td>
                                <td>
                                    <div class="rating"><span style="width:100%" class="ratingwidth">4.8</span><span class="ratingblank"></span>
                                    </div>
                                </td>
                                <td>1-2 Days</td>
                                <td>-</td>
                                <td class="seller_total1475">₹ 0.00</td>
                                <td>
                                    <input id="button-1475" value="select" class="selectvendor" sellerid="1475" for="radio-1" type="button">
                                    <input class="clickmetoselect1" style="display:none;margin:4px 7px 0 0" moq="-" seller-name="Shankara Infrastructure Materials Ltd" name="vendor" value="1475" id="radio-1475" type="radio">
                                </td>

                            </tr>
                            <tr class="clickmetoselect cust-trb">
                                <td>Srinivasa Steel Traders (10000109)</td>
                                <td>
                                    <div class="rating"><span style="width:100%" class="ratingwidth">4.8</span><span class="ratingblank"></span>
                                    </div>
                                </td>
                                <td>1-2 Days</td>
                                <td>-</td>
                                <td class="seller_total1522">₹ 0.00</td>
                                <td>
                                    <input id="button-1522" value="select" class="selectvendor" sellerid="1522" for="radio-1" type="button">
                                    <input class="clickmetoselect1" style="display:none;margin:4px 7px 0 0" moq="-" seller-name="Srinivasa Steel Traders" name="vendor" value="1522" id="radio-1522" type="radio">
                                </td>

                            </tr>

                            <tr class="clickmetoselect cust-trb">
                                <td>Gee Dee Enterprises (10000248)</td>
                                <td>
                                    <div class="rating"><span style="width:100%" class="ratingwidth">4.8</span><span class="ratingblank"></span>
                                    </div>
                                </td>
                                <td>1-2 Days</td>
                                <td>-</td>
                                <td class="seller_total2677">₹ 0.00</td>
                                <td>
                                    <input id="button-2677" value="select" class="selectvendor" sellerid="2677" for="radio-1" type="button">
                                    <input class="clickmetoselect1" style="display:none;margin:4px 7px 0 0" moq="-" seller-name="Gee Dee Enterprises" name="vendor" value="2677" id="radio-2677" type="radio">
                                </td>

                            </tr>

                        </tbody>




                    </table>

                </div>

            </div>
            <!--select_seller start-->

        </div>
        <!-- well block end-->

    </div>
    <!-- choose seller end-->





</div>
<!-- wrapper end-->