<?php
// Get Custom card Details
$customcard = Mage::registry( 'customcard' );
?>

<p>Redirecting... If you have been here for a while, please <a href="#">click here</a>.</p>
<p>Make sure you don't press the 'Back' button in your browser till your order is complete.</p>

<form name="customcardform" method="post" action="<?php echo $customcard['action']; ?>">
</form>

<script type="text/javascript">
document.customcardform.submit();
</script>
