<div id="checkout_design">
<div class="wrapper-container-checkout">

    <div class="checkout_inner">
		<!--<div class="page-title">
			<h1><?php // echo $this->__('Checkout') ?></h1>
		</div>-->
		<div class="checkout-err  clear">
			<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
		</div>
		<script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
		<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>
		<ol class="opc" id="checkoutSteps">
		<?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
		<?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
			<li id="opc-<?php echo $_stepId ?>" class="section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
				<div class="step-title">
					<h3 class="col-lg-9 col-md-9 col-sm-9 col-xs-8">Step <?php echo $i ?>: <?php echo $_stepInfo['label'] ?></h3>
					<a href="#" class="col-lg-2 col-md-2 col-sm-2 col-xs-2 text-right edit_change" id="edit_<?php echo $_stepId ?>"><span class="glyphicon glyphicon-pencil pencil_icon"></span><?php echo $this->__('Edit') ?></a>
					<div class="col-lg-1 col-md-1 col-sm-1 col-xs-2 aliging_ok tick_ok" id="tick_<?php echo $_stepId ?>"><span class="glyphicon glyphicon-ok ok_icon"></span></div>
				</div>
				<div id="checkout-step-<?php echo $_stepId ?>" class="step a-item" style="display:none;">
				
					<?php echo $this->getChildHtml($_stepId) ?>
				</div>
			</li>
		<?php endforeach ?>
		</ol>
   </div>
   
</div></div>
<script type="text/javascript">
//<![CDATA[
    var accordion = new Accordion('checkoutSteps', '.step-title', true);
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
    <?php endif ?>
    var checkout = new Checkout(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
//]]>
</script>
<script>
jQuery(document).ready(function(){
		jQuery(".edit_change,.tick_ok").addClass("edit_icon_hide");
		jQuery(".check_billing").click(function(){
				jQuery("#edit_billing,#tick_billing").removeClass("edit_icon_hide");
		});
		jQuery("#shipping-buttons-container button").click(function(){			
			jQuery("#edit_shipping,#tick_shipping").removeClass("edit_icon_hide");
		});
		jQuery("#payment-buttons-container button").click(function(){			
			jQuery("#edit_payment,#tick_payment").removeClass("edit_icon_hide");
		});		
		jQuery("#edit_billing,#tick_billing,#opc-billing .step-title").click(function(){	
				jQuery(".edit_change,.tick_ok").addClass("edit_icon_hide");
		});
		jQuery("#edit_shipping,#tick_shipping,#opc-shipping .step-title").click(function(){	
				jQuery("#edit_payment,#tick_payment,#edit_shipping,#tick_shipping").addClass("edit_icon_hide");
		});
		jQuery("#edit_payment,#tick_payment,#opc-payment .step-title").click(function(){	
				jQuery("#edit_payment,#tick_payment").addClass("edit_icon_hide");
		});
});
</script>
<script>
	jQuery('.addressbox').click(function(){
		var sel = jQuery(this).attr('data-box');
		jQuery('.addressbox').removeClass("selected");
		jQuery('#'+sel).val(jQuery(this).attr("id"));
		jQuery(this).addClass("selected");
		jQuery('#billing-new-address-form').css("display","none");
		jQuery('#shipping-new-address-form').css("display","none");
		jQuery('.addnew').css("display","inline");
		jQuery('.cancel-btn').css("display","none");
		selectedPincode = jQuery(this).attr('data-zipcode');
		selectedBillingPincode = jQuery(this).attr('data-billing-zipcode');
		});
	jQuery('.addnewaddress').click(function(){
		var sel = jQuery(this).attr('data-box');		
		if(sel == 'billing-address-select'){
			var addcount = jQuery('.addressbox').attr('data-count');						
			if(addcount >= 6){
				jQuery(".addlimit").html('Please delete one of the existing addresses before adding a new address.');	
				jQuery( ".addnewaddress" ).prop( "disabled", true );
			}else{
				jQuery(".addlimit").html('');
				jQuery( ".addnewaddress" ).prop( "disabled", false );
				var sel = jQuery(this).attr('data-box');
				jQuery('#'+sel).val('').change();
				jQuery('.addressbox').removeClass("selected");
				jQuery('.addnew').css("display","none");
				jQuery('.cancel-btn').css("display","inline");
			}
		}else{			
			var addcount = jQuery('.addressbox').attr('data-count');					
			if(addcount >= 5){
				jQuery(".addlimit").html('Please delete one of the existing addresses before adding a new address or select existing address.');	
				jQuery( ".addnewaddress" ).prop( "disabled", true );
			}else{
				jQuery(".addlimit").html('');
				jQuery( ".addnewaddress" ).prop( "disabled", false );
				var sel = jQuery(this).attr('data-box');
				jQuery('#'+sel).val('').change();
				jQuery('.addressbox').removeClass("selected");
				jQuery('.addnew').css("display","none");
				jQuery('.cancel-btn').css("display","inline");
			}
		}

		
		
	});
	jQuery('.cancel').click(function(){
		var billid = '<?php echo Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling() ?>';
		jQuery("#co-billing-form #"+billid).addClass("selected");
		jQuery('#billing-new-address-form').css("display","none");
		jQuery('#shipping-new-address-form').css("display","none");
		jQuery('.cancel-btn').css("display","none");
		jQuery('.addnew').css("display","inline");
		//jQuery('.full-ship-top').css("display","block");
	});
	jQuery('.check_billing').click(function(){
		jQuery(".addlimit").html('')
		jQuery( ".addnewaddress" ).prop( "disabled", false );
		var billingval = jQuery('#billing-address-select').val();
		if(billingval)
		{	
		jQuery("#co-billing-form #"+billingval).addClass("selected");
		selectedBillingPincode = jQuery("#co-billing-form #"+billingval).attr('data-billing_zipcode');
		}
		jQuery('#shipping-new-address-form').css("display","none !important");
		var result = jQuery("span").hasClass("error1");
		if(result != true){
			jQuery('#'+billingval).trigger( "click" );
		}
		var shipid = '<?php echo Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping() ?>';
		if(shipid)
		{
		jQuery("#co-shipping-form #"+shipid).addClass("selected");
		selectedPincode = jQuery("#co-shipping-form #"+shipid).attr('data-zipcode');
		}
		jQuery('.cancel-btn').css("display","none");
		jQuery('.addnew').css("display","inline");
	});
	jQuery('.check_shipping').click(function(){
		jQuery(".addlimit").html('')
		});	
	jQuery('.step-title').click(function(){
		
		jQuery('.cancel-btn').css("display","none");
		jQuery('.addnew').css("display","inline");
		var selbill = jQuery('#billing-address-select').val();
		jQuery("#co-billing-form #"+selbill).addClass("selected");
	});
</script>
<script type="text/javascript">
	function deleteAddress(addressId) {
		if(confirm('Are you sure you want to delete this address?')) {
			window.location='<?php echo $this->getUrl('customer/address/delete') ?>id/'+addressId;
		}
		return false;
	}
</script>
