<div class="wrapper-container-cart">
<div class="cart">
    <div class="cart-title"><h1>shopping list</h1></div>

    <div class="cart-message-top" style="display:none;">
	<?php echo $this->getMessagesBlock()->toHtml() ?>
   </div>

    <?php echo $this->getChildHtml('form_before') ?>

    <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">

        <?php echo $this->getBlockHtml('formkey'); ?>

        <fieldset>
    <div style="overflow:auto"> 

            <table class="cart-table bdtable table table-condensed">
            <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>

                <thead class="bdtop">

                    <tr class="first shp-body">

                        <th rowspan="<?php echo $mergedCells; ?>" class="hidden-mobile"> <span class="nobr theadtxt">Item</span></th>
                        <th class="desktop-display" rowspan="<?php echo $mergedCells; ?>"><span class="nobr theadtxt"><?php echo $this->__('Product Name') ?></span></th>
                        <th class="desktop-display" rowspan="<?php echo $mergedCells; ?>"><span class="nobr theadtxt"><?php echo $this->__('Seller Name') ?></span></th>

                        <!--<th rowspan="<?php echo $mergedCells; ?>" class="hidden-mobile"></th>-->

                        <?php /*if ($this->helper('wishlist')->isAllowInCart()) : ?>

                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center hidden-mobile"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>

                        <?php endif*/ ?>

                        <th colspan="<?php echo $mergedCells; ?>"><span class="nobr theadtxt"><?php echo $this->__('Unit Price') ?></span></th>
                        <th colspan="<?php echo $mergedCells; ?>"><span class="nobr theadtxt"><?php echo $this->__('VAT Percent') ?></span></th>

                        <th rowspan="<?php //echo $mergedCells; ?>" class="a-center theadtxt desktop-display"><?php echo $this->__('Qty') ?></th>

                        <th colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>

                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center theadtxt">Action</th>

                    </tr>

                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>

                    <tr>

                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>

                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>

                        <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>

                        <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>

                    </tr>

                    <?php endif; ?>

                </thead>

    <!-- footer tfoot comes here-->
    


                <tbody>

                <?php foreach($this->getItems() as $_item): ?>

                    <?php echo $this->getItemHtml($_item) ?>

                <?php endforeach ?>

                </tbody>

            </table>

            
</div>
            <script type="text/javascript">decorateTable('shopping-cart-table')</script>

        </fieldset>



    </form>

   <!-- <div class="orderyxy mt15">order adjustments</div>-->
    <div class="cart-collaterals">



       <div class="row">     
<div class="col-2 col-lg-6 col-md-6 col-sm-6 col-xs-12">
<div class="well-block mh35  white-bg">

                    <?php /* Extensions placeholder */ ?>

                    <?php echo $this->getChildHtml('checkout.cart.extra') ?>

                    <?php echo $this->getChildHtml('coupon') ?>

                   
             <!--   <div class="col-1 col-lg-4 col-md-4 col-sm-4 col-xs-12 ">

                    <?php echo $this->getChildHtml('crosssell') ?>

                </div>-->

        <!--       <div class=" col-lg-12 col-md-12 col-sm-12 col-xs-12 padbd">

                    
                <div class="col-2 col-lg-6 col-md-6 col-sm-6 col-xs-12">

                    <?php /* Extensions placeholder */ ?>

                    <?php echo $this->getChildHtml('checkout.cart.extra') ?>

                    <?php echo $this->getChildHtml('coupon') ?>

                    </div>


                    <div class="col-2 col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="coupform">

                        

                        <div class="discount-form pad15">

                           
                            <div class="input-box boxlength">

                                <input value="" name="reffer_by" id="reffer_by" class="input-text coupinput" placeholder="who refered you?">
                                <div class="reffer_error"></div>
                            </div>

                            <div class="coupbtn">
                                
                                <button value="Submit" class="cbtn" title="Submit" type="button"><span><span>Submit</span></span></button>

                                            </div>

                        </div>

                    </div>
                </div>
            
            </div>-->
                    <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>

                
			<!--	<div class="convenience"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('convenience')->toHtml();?></div>-->

				</div>
				</div>
				
				                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 fright">
						<div class="well-block mh35">
                    <div class="chktotals">
			<div class="discount">
        <h2	><?php echo $this->__('List Total') ?></h2> 
</div>
                        <?php echo $this->getChildHtml('totals'); ?>
						<div class="col-lg-8 col-md-6 col-xs-12 col-sm-12 ot-msg">
							*Other charges may be applicable
						</div>
						<div class="col-lg-4 col-md-6 col-xs-12 col-sm-12 chechout-sbtn">
<!-- checkoye btn-->
                        <?php if(!$this->hasError()): ?>

                        <div class="checkout-types chkop">
                        
                      

                        

                        <?php foreach ($this->getMethods('methods') as $method): ?>

                            <?php if ($methodHtml = $this->getMethodHtml($method)): ?>

                           <?php echo $methodHtml; ?>

                            <?php endif; ?>

                        <?php endforeach; ?>

                        </div>

                        <?php endif; ?>
						</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pad0 shopping-cart-btn">	
<div class="desktop-display">
To Continue Shopping, click <a class="mt5 contshop-btn"  title="<?php echo $this->__('Continue Shopping') ?>" href="<?php echo Mage::getBaseUrl(); ?>"><?php echo $this->__('here') ?></a>
	</div>

	<div class="mobile-display">
 <a class="mt5 contshop-btn"  title="<?php echo $this->__('Continue Shopping') ?>" href="<?php echo Mage::getBaseUrl(); ?>"><?php echo $this->__('Continue Shopping') ?></a>
	</div>
	</div>	
<!-- end-->
                    </div>

                </div>
				
				
				</div>	<!-- well block end-->
				
</div><!-- row end-->
        

        </div>

   

</div>

<style type="text/css">
.reffer-validation-success{
color:#3d6611;
}
</style>

<script type="text/javascript">
jQuery(document).ready(function(){
    jQuery(".reffer_btn").click(function(){
        jQuery(".reffer_error").html("");
        jQuery(".reffer_error").removeClass("validation-advice");
        
        var reffer_by = jQuery("#reffer_by").val();
        if(reffer_by){
            jQuery.ajax({
                method: "POST",
                url: "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>reffer/index/index",
                data: { reffer_by: reffer_by },
                success:function( msg ) {
                    jQuery(".reffer_error").addClass("reffer-validation-success");
                    jQuery(".reffer_error").html(msg);
                }
            });
        }else{
            jQuery(".reffer_error").addClass("validation-advice");
            jQuery(".reffer_error").html("Please Enter Refferer Name.");
        }
    });
});
</script>


<style type="text/css">
.ot-msg{ margin-top:1em;font-size:10px;}
.ot-txt-msg{ font-size:10px;}

</style>
</div>
