<form id="co-shipping-form" action="">
   <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mt20 pad10">
      <div class="ship-address form-list" id="shipping_fields">
         <h2>Shipping Information</h2>
         <?php if ($this->customerHasAddresses()): ?>
         <!-- <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label> -->
         <div class="field">
            <div class="input-box">
               <div style="display:none;"> <?php echo $this->getAddressesHtmlSelect('shipping') ?></div>
               
               <?php $customerId = Mage::getSingleton('customer/session')->getCustomer();?>    
				<?php $customer = Mage::getModel('customer/customer')->load($customerId->getId()); ?>
				<?php $data = array();?>
				
				<?php $address = $customer->getAddresses(); ?>
				<?php $i = 0; ?>
				<?php $no = count($address); ?>
				
				<?php foreach ($address as $addr):?>
				<?php $data = $addr->toArray();?>
				<?php if($i >= ($no-6)) { ?>
				<div id="addresseList<?php echo $data['entity_id'];?>">
					<div id="<?php echo $data['entity_id'];?>" data-box="shipping-address-select" data-count1="<?php echo $no ?>" data-zipcode="<?php echo $data['postcode'] ;?>" class="addressbox">
						<address class="bill-ship-block">                      
							<?php echo '<p class="last-first-name"><b>'.$data['firstname'].' '.$data['lastname'].'</b></p>';?>
							
						<a class="group1" href="<?php echo Mage::getBaseUrl() . 'customer/address/edit/id/' . $data['entity_id']; ?>?popupEdit=1&meth=billing" ><i class="fa fa-pencil"></i></a>
						<a href="#" class="link-remove" onclick="return deleteAddress('<?php echo $data['entity_id'];?>');"><i class="fa fa-trash-o"></i></a>
							<?php echo '<p>'.$data['street'].'</p>';?>
							<?php echo '<p>'.$data['city'].','.$data['region'].','.$data['postcode'].'</p>';?>
							<?php $country_name = Mage::app()->getLocale()->getCountryTranslation($data['country_id']);?>
							<?php echo '<p>'.$country_name.'</p>';?>
							<?php echo '<p> T: '.$data['telephone'].'</p>';?>
						</address>
					</div>
					
				</div>
				<?php } $i++;?>
				<?php endforeach;?>
				 
				
				
            </div>
         </div>
         <?php endif ?>
         <ul>
            <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
               <fieldset id="shipping_fieldset" class="shipping_form">
                  <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
                     </div>
                  </div>
                  
                  <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <input type="text" placeholder="* Address Line 1" title="<?php echo $this->__('Address Line 1') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                     </div>
                  </div>
                  <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                  <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box shipping_address2">
                        <input type="text" placeholder="Address Line 2" title="<?php echo $this->__('Address Line %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="input-text <?php echo $_streetValidationClass ?>" onchange="shipping.setSameAsBilling(false);" />
                     </div>
                  </div>
                  <?php endfor; ?>
				  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                      <input type="text"  maxlength="10" placeholder="* Telephone" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="mobileship input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
				     </div>
                  </div>
                  <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                     </div>
                  </div>
                  <?php endif; ?>
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <!--<input type="text" placeholder="* City"  title="<?php echo $this->__('City') ?>" name="shipping[city]" value="Bangalore" class="cityy input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" readonly="readonly"  />-->
						<select title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="cityy validate-select <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" >
						<option value=""><?php echo $this->__('Please select city') ?></option>
						<option value="Bangalore"><?php echo $this->__('Bangalore') ?></option>
						<option value="Mysore"><?php echo $this->__('Mysore') ?></option>
						</select>
                     </div>
                  </div>
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="statee shipping_fileds validate-select" style="display:none;" disabled>
                           <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                           //<![CDATA[
                            $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                           //]]>
                        </script>
                        <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="statee input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                     </div>
                  </div>
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12">
                     <div class="input-box">
                        <input type="text"  maxlength="6" placeholder="* Zip/Postal Code" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="zipship shipping_fileds input-text required-entry <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsBilling(false);" />
                     </div>
                  </div>
                  <div class="field col-lg-6 col-md-6 col-sm-6 col-xs-12" style="float:right">
                     <div class="input-box">
                        <?php echo $this->getCountryHtmlSelect('shipping') ?>
                     </div>
                  </div>
               </fieldset>
            </li>
         </ul>
         <div class="full-ship "style="display:none;">
            <div class="biling-ship-address field col-lg-6 col-md-6 col-sm-6 col-xs-12" style="float:right; height: 40px">
               <div class="ship-left control shiping-rinput" >
                  <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                  <input type="checkbox" checked="checked" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" />
                  <label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                  <?php else:?>
                  <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                  <?php endif;?>
               </div>
               <div class="ship-left control shiping-rinput">
                  <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" />
                  <label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label> 
               </div>
            </div>
         </div>
		 
		 <!-- Exception pincode Start -->
		 <?php $pincodelistBangalore = Mage::getStoreConfig('configuration/configuration_exception_pincode/bangaloreexceptionpincodes'); ?> 
         <input type="hidden" name="bangalore_exception_pincode" id="bangalore_exception_pincode" value="<?php echo $pincodelistBangalore; ?>" />
		 
		 <?php $pincodelistMysore = Mage::getStoreConfig('configuration/configuration_exception_pincode/mysoreexceptionpincodes'); ?> 
         <input type="hidden" name="mysore_exception_pincode" id="mysore_exception_pincode" value="<?php echo $pincodelistMysore; ?>" />
		  <!-- Exception pincode End -->
		  
		
         <div class="buttons-set" id="shipping-buttons-container">
            <!-- <p class="required"><?php echo $this->__('* Required Fields') ?></p>-->
            <!--   <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>-->
            <div class="addlimit" style="color: #bf4a32;font-size: 13px;text-align: center;"></div>
			<div class="col-lg-12 col-sm-12 col-md-12 col-xs-12 text-center">
            <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
			
			<span class="addnew">
					<button type="button" class="addnewaddress" data-box = "shipping-address-select" id="billing_add" value="<?php echo $this->__('Add New Address');?>"/>Add New Address</button>
			</span>
			<span class="cancel-btn" style="display:none;">
					<button type="button" class="addnewaddress cancel" data-box="shipping-address-select" id="billing_cancel" value="<?php echo $this->__('Cancel');?>">Cancel</button>
			</span>
			<?php endif;?>
			<span>
				<button type="button" class="check_shipping button" title="<?php echo $this->__('Continue') ?>"><span><span><?php echo $this->__('SAVE AND CONTINUE') ?></span></span></button>
			</span>
            <span id="shipping-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
            </span>
			</div>
         </div>
      </div>
   </div>
</form>
<script type="text/javascript">
   //<![CDATA[
       var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
           '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
       var shippingForm = new VarienForm('co-shipping-form');
       shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
       //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
       $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);
    jQuery('#shipping\\:country_id option[value=""]').hide();
       var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
   //]]>
</script>
<script type="text/javascript">
		var selbill = jQuery('#shipping-address-select').val();
	jQuery("#co-shipping-form #"+selbill).addClass("selected");
//jQuery(".input-box div:nth-child(2) .addressbox").addClass("selected")
   jQuery(".statee").val('501');
   jQuery("#shipping-address-select").val("");
   jQuery("#shipping-new-address-form").css("display", "block");
   
   jQuery(".check_shipping").click(function(){
   
   jQuery('.statee').val('501').attr("selected", "selected"); 
   jQuery(".zipship").blur(function(){
    selectedPincode = jQuery(this).val();
    });
   cityy = jQuery(".cityy").val();
   statee = jQuery(".statee").val();
   zip = jQuery(".zipship").val();
   selectedPincode = zip;

   var cartcount = '<?php echo Mage::helper('checkout/cart')->getItemsCount(); ?>';
		 <?php 
			$quote = Mage::getSingleton('checkout/session')->getQuote();
			$cartItems = $quote->getAllVisibleItems();
			foreach ($cartItems as $item) {
				if($productZip == $item->getZipcode()){
					$productZip = $item->getZipcode();
				}else{
					$productZip = $item->getZipcode();
				}
			}
		 ?> 
		  var zipvalidate = '<?php echo $productZip  ?>';
		  <?php $zipcodemsg =  Mage::getStoreConfig('configuration/configuration_checkout_zipcode_validation/checkoutzipcode'); ?>
		  var zipcodemsg = '<?php echo $zipcodemsg ?>';
		  var finalmnsg =  zipcodemsg.replace('{{old_pincode}}',zipvalidate).replace('{{new_pincode}}',zip);
		  if(zipvalidate == selectedPincode)
		  {
			  shipping.save();
		  }
		  else
		  {
			  alert(finalmnsg);  
			  return false;
		  }
		   
   
   var full_address_value_ship = jQuery('#shipping-address-select option:selected').text();
   full_address_value_ship = full_address_value_ship.toLowerCase();
   if(full_address_value_ship != 'new address' && full_address_value_ship != "")
   		{
   		if(full_address_value_ship.indexOf('bangalore') > -1 ||  full_address_value_ship.indexOf('bangaluru') > -1 || full_address_value_ship.indexOf('bengaluru') > -1 || full_address_value_ship.indexOf('mysore') > -1 || full_address_value_ship.indexOf('mysuru') > -1)
   		{
   			if(full_address_value_ship.indexOf('karnataka') > -1)
   			{
   			shipping.save();
   			}
               else
   			{
   			alert("Currently delivering in Bangalore & Mysore only.");
   			}				
   		}
           else
           {
   		alert("Currently delivering in Bangalore & Mysore only.");	
   		}			
   		} 
   else
   {	   
   if(cityyLower == 'bangalore' || cityyLower == 'bangaluru' || cityyLower == 'bengaluru' || cityyLower == 'mysore' || cityyLower == 'mysuru' && statee == 501)
   {
   
    var hasErrorship1 = false; 
    var mobiRegship = /^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[789]\d{9}$/;
    //var mobiRegship1 = /^(?:[2-9][0-8][0-9])(?!(\d)\1+$)([2-9][0-9]{2}[0-9]{4})$/;
    jQuery(".error1ship").hide();
    var mobileshipshipVal = jQuery(".mobileship").val();
    
   
       if(mobileshipshipVal == '') {
           jQuery(".mobileship").after('<span class="error1ship">Enter mobile number.</span>');
           hasErrorship1 = true;
       }
   
       else if(!mobiRegship.test(mobileshipshipVal)) {
           jQuery(".mobileship").after('<span class="error1ship">Enter Valid mobile Number.</span>');
           hasErrorship1 = true;
       }
    else
    {
      jQuery(".error1ship").hide(); 
    }
   
   
          jQuery(".error2ship").hide();
          var haserror2ship = false;
          var zipcodestartship= 560000;
          var zipcodeendship = 560300;
		  
		  var zipcodestartshipMysore = 570000;
          var zipcodeendshipMysore = 570027;
          
          var zipcodekValship = jQuery(".zipship").val();
          
         
          
		  
		  var bangaloreExceptionpin = jQuery("#bangalore_exception_pincode").val();
		  var bangaloreExceptionArray = bangaloreExceptionpin.split(',');
		  var mysoreExceptionpin = jQuery("#mysore_exception_pincode").val();
		  var mysoreExceptionArray = mysoreExceptionpin.split(',');
		       
          if(cityy == 'Bangalore')	  
	      {
          if(zipcodekValship == '') {
            jQuery(".zipship").after('<span class="error2ship">Enter Zip Code.</span>');
            haserror2ship = true;
          }
          else if(((zipcodekValship > zipcodestartship && zipcodekValship < zipcodeendship) == false) && (jQuery.inArray(zipcodekValship, bangaloreExceptionArray) == -1)) {
            jQuery(".zipship").after('<span class="error2ship">Enter Bangalore Zip Code.</span>');
            haserror2ship = true;
          } 
		  }
		  else if(cityy == 'Mysore')
		  {
		    if(zipcodekValship == '') {
            jQuery(".zipship").after('<span class="error2ship">Enter Zip Code.</span>');
            haserror2ship = true;
            }
            else if(((zipcodekValship > zipcodestartshipMysore && zipcodekValship < zipcodeendshipMysore) == false) && (jQuery.inArray(zipcodekValship, mysoreExceptionArray) == -1)) {
            jQuery(".zipship").after('<span class="error2ship">Enter Mysore Zip Code.</span>');
            haserror2ship = true;
            }	
		  }	  
		  
		  
    
          jQuery(".error3ship").hide();
            var haserror3ship = false;
            var nameregexship =/^[a-zA-Z. ]+$/;
            var nameaddressValship = jQuery(".myfirstnameship").val();
            
            if(!nameregexship.test(nameaddressValship)) {
                jQuery(".myfirstnameship").after('<span class="error3ship">Enter Valid First Name.</span>');
                haserror3ship = true;
          }else{
          jQuery(".error3ship").hide(); 
          }
          
          jQuery(".error4ship").hide();
            var haserror4ship = false;
            var addressregexship =/^[a-zA-Z0-9\/\-.,#_ ]+$/i;
            var addressValship = jQuery(".streetship1").val();
            if(!addressregexship.test(addressValship)) {
                jQuery(".streetship1").after('<span class="error4ship">Enter Valid Address.</span>');
                haserror4ship = true;
          }
          else
          {
            jQuery(".error4ship").hide(); 
          }
            
          jQuery(".error5ship").hide();
          var haserror5ship = false;
          var lnameregexship =/^[a-zA-Z. ]+$/;
          var lnameaddressValship = jQuery(".mysecnameship").val();
          if(!lnameregexship.test(lnameaddressValship)) {
              jQuery(".mysecnameship").after('<span class="error5ship">Enter Valid Last Name.</span>');
              haserror5ship = true;
            }
            else{
            jQuery(".error5ship").hide(); 
            }
          
          var address2Valshipemty = jQuery(".streetship2").val();
          
          if(!address2Valshipemty == ''){  
            
            jQuery(".error6ship").hide();
              var haserror6ship = false;
              var address2regexship = /^[a-zA-Z0-9\/\-.,#_ ]+$/i;
              var address2Valship = jQuery(".streetship2").val();
              if(!address2regexship.test(address2Valship)) {
                  jQuery(".streetship2").after('<span class="error6ship">Enter Valid Address.</span>');
                  haserror6ship = true;
            }
            else
            {
            jQuery(".error6ship").hide(); 
            }
            if(haserror6ship == true) { return false; }
          }  
       
       if(hasErrorship1 == true)
       {
        return false; 
       }
            else if(haserror2ship == true)
            {
        return false;
       }
       else if(haserror3ship == true)
            {
        return false;
       }
       else if(haserror4ship == true)
            {
        return false;
       }
       else if(haserror5ship == true)
            {
        return false;
       }
       else
       {
       shipping.save();    
       }      
   }  
   else
   {
   alert("Currently delivering in Bangalore & Mysore only.");  
   }
   }
    
   });
   
</script>


