<?php
/**
 * Created by Magentix
 * Based on Module from "Excellence Technologies" (excellencetechnologies.in)
 *
 * @category   Magentix
 * @package    Magentix_Convenience
 * @author     Matthieu Vion (http://www.magentix.fr)
 * @license    This work is free software, you can redistribute it and/or modify it
 */
?>

<?php if($this->getSource() instanceof Mage_Sales_Model_Order): ?>

    <?php if ((float)$this->getSource()->getConvenienceAmountRefunded() > 0): ?>
        <tr>
            <td class="label"><strong><?php echo Mage::helper('convenience')->__('Convenience refunded to customer') ?></strong></td>
            <td><strong><?php echo $this->getSource()->getConvenienceAmountRefunded(); ?></strong></td>
        </tr>
    <?php endif; ?>

<?php else: ?>

    <?php if ((float)$this->getSource()->getConvenienceAmount()): ?>
        <tr>
            <td class="label"><strong><?php echo Mage::helper('convenience')->__('Convenience Refunded') ?></strong></td>
            <td><strong><?php echo $this->getSource()->getConvenienceAmount(); ?></strong></td>
        </tr>
    <?php endif;  ?>

<?php endif; ?>

