<?php $_code=$this->getMethodCode() ?>
<div>

<ul class="form-list col-lg-12 col-md-12 col-sm-12 col-xs-12 mt20 pad10" id="payment_form_<?php echo $_code ?>" style="display:none; width:100% !important;">

    <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
        <input type="text" placeholder="*<?php echo $this->__('Cheque No#') ?>" title="<?php echo $this->__('Check No#') ?>" class="input-text required-entry validate-number" id="<?php echo $_code ?>_check_no" name="payment[check_no]" value="<?php echo $this->htmlEscape($this->getInfoData('check_no')) ?>" />
    </span>

	<div class="our-dd col-lg-6 col-md-6 col-sm-6 col-xs-6">
		<div class="our-dd-local">
	       <input class="radio" type="radio" id="<?php echo $_code ?>_cheqloc" name="payment[cheqloc]" value="1" /> <span>Local DD</span>
		</div>
	    <div class="our-dd-out">
			<input class="radio" type="radio" id="<?php echo $_code ?>_cheqloc" name="payment[cheqloc]" value="2" /> <span>Outstation DD</span>
		</div>
	</div>
	
	<span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
	<input  class="mydate" name="payment[check_date]" value="<?php echo $this->htmlEscape($this->getInfoData('check_date')) ?>" id="<?php echo $_code ?>_check_date" placeholder="*<?php echo $this->__('Cheque Date(mm/dd/yy):') ?>" title="<?php echo $this->__('Cheque Date(mm/dd/yy):') ?>" readonly class="input-text required-entry" type="text">
            <script type="text/javascript">
			//var $a = jQuery.noConflict();
            //<![CDATA[
                // Calendar.setup({
                    // inputField: "<?php echo $_code ?>_check_date",
                    // ifFormat: "%m/%e/%Y",
                    // showsTime: false,
                    // button: "shipping_arrival_date_trig",
                    // align: "Bl",
					// disableFunc: function(date) {
// var now= new Date();
// if(date.getFullYear() < now.getFullYear()) { return true; }
// if(date.getFullYear() == now.getFullYear()) { if(date.getMonth() < now.getMonth()) { return true; } }
// if(date.getMonth() == now.getMonth()) { if(date.getDate() < now.getDate()) { return true; } }
// },
                    // singleClick : true
					
                // });
            //]]>
			

	  jQuery(function() {
		jQuery( "#<?php echo $_code ?>_check_date" ).datepicker({
		  showOn: "button",
		  buttonImage: "<?php echo Mage::getBaseUrl('skin')?>adminhtml/default/default/images/grid-cal.gif",
		  buttonImageOnly: true,
		  buttonText: "Select date",
		   minDate: 0 // 0 days offset = today
		});
	  });


	jQuery("#<?php echo $_code ?>_check_date").on("click", function() {
		jQuery("#<?php echo $_code ?>_check_date").datepicker("show");
	});
            </script>
    </span>
	
	<span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
    <input type="text" placeholder="*<?php echo $this->__('PAN Number ') ?>" title="<?php echo $this->__('PAN Number ') ?>" class="input-text required-entry" id="<?php echo $_code ?>_panno" name="payment[panno]" value="<?php echo $this->htmlEscape($this->getInfoData('panno')) ?>" />
    </span>
	
	
	 <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
        <input type="text" placeholder="*<?php echo $this->__('Drawee Name') ?>" title="<?php echo $this->__('Drawee Name') ?>" class="input-text required-entry" id="<?php echo $_code ?>_draweename" name="payment[draweename]" value="<?php echo $this->htmlEscape($this->getInfoData('draweename')) ?>" />
    </span>
	
    
<script type="text/javascript">
//<![CDATA[
	// Calendar.setup({
		// inputField: "_dob",
		// ifFormat: "%m/%e/%y",
		// showsTime: false,
		// button: "_dob_trig",
		// align: "B1",
		// singleClick: true
	// });
	//]]>
</script>

  
    <span class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
        <input type="text" placeholder="*<?php echo $this->__('Drawee Bank') ?>" title="<?php echo $this->__('Drawee Bank') ?>" class="input-text required-entry" id="<?php echo $_code ?>_draweebank" name="payment[draweebank]" value="<?php echo $this->htmlEscape($this->getInfoData('draweebank')) ?>" />
    </span>
	
  	
	


	
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
